apiVersion: ENC[AES256_GCM,data:dm4=,iv:mA6VAa4DiH7wuMkg+H+ZiixWfB45I3Lli4edRgjNotM=,tag:dfDxOQWjSkY5CHDinfxJow==,type:str]
kind: ENC[AES256_GCM,data:uGpJhnKO,iv:Gd4USY4ZWmO8r8rXkldA/LcfBYDwdA58EU5htWw6P9Q=,tag:Co3Im6aMRpFr+YGO7J4Ayw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eUXmPLOvR6crtFSkoxY=,iv:p9iiqVC1DHZaWE6tKXPmOz2fZSC/AEZt9lIydHlUlFg=,tag:yi8edomDFq5Dx+/L++qvTg==,type:str]
    namespace: ENC[AES256_GCM,data:QxYbxlHSmUYHUQ==,iv:GbVpcz78RUypTC4UyQcfopT4KW2JQetAD9czC8T5g4Y=,tag:7pVRva6afmg+ArrzRPW3ng==,type:str]
stringData:
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:dgN6pecl0tAX1JWtvJQiUwbxG6g=,iv:twKeHzl0E544okv7c1im26/rBfNlD3PJ/TNm2lR7ppo=,tag:K5GtZ1Lus25wq4vynCElfg==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:GbYRxdwuoLM1TKAfjsuqAspH89bdOmKIZqH+QRMPLyDUweJ3oH6bQA==,iv:rWAz85WOirvHLuai8OTKx3c9JnjMcl1vYwwdtImpROU=,tag:0+tqPJQCl3g7RxlbU/6ulA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:BSZXxkn/LGPazW7bBj/g+55ARGk83sJKY/i5OVVK3PgWQ5XtZWy+yZAUAVkZAAtihT0Q6NXfDK4Qsr7C4C70kw==,iv:eahdpwBVcxN2a1XP5uFSgvHpFZp/vY3RZ6Hk66/Zmrk=,tag:LrYlB2qlFLQp5BDnwd7vAg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Ok8hpEQS,iv:ZXJVd0qUWpTU49iHcqIhPQU2tN8whM54LK7UPpxp9Pk=,tag:hVROD0nENUSRR7c7Ltpj2A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:yzIVyjgitjuSmJLBbbzSkDuNAMCGbpn5moAvhb+d5w==,iv:XAdgUe+oJOeAPmKdrYCiz+Tx53a+FP0XYsaqxaX5AsI=,tag:inLwuSTXUdm/PGTvGLoZJQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:tyHL6ySo,iv:PwcLewe68zPefuYlt5Zm0XULy3v8syiWbGz1jSSrlpg=,tag:kfQ4GbiORmUVISByi25SGw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:AWqEfv0yaEtVfaoxZYd5oQnt+smPGWqAL5p9c7V6ITTxDgZDGtSgxN2SOn0/nPNvmstNHsy/3UfTp4FqiJcDdVyosblQ9pQWH3cyjT/WPV27tbOWOaAI4e7fo0t6IH0/4KC/02135UJ70/jM7LU=,iv:2hwTJIGmXgG7P00TnnfF0M1VAaax9hY0X3oEuFlt0Ow=,tag:XplXYvZgRhCA2OBoK4fXlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQlYzSlFrNHFFSFBNR0JN
            Z2dRS3NFVlo3VWRJcitXQ1RUSUhoL0lHQkdBCitzREJrY1hPYXF5dWdMN2U5UGhj
            cUZNUjFYRVFZZjhHKzByNHRJSDN1VFUKLS0tIHJFRnlLYWt0S3FTR0hYdXlCbUZo
            UXJDWmxwVmFvNEJMd0NlenJhUmdUZ2cKGYhOxkPwjdNTKbHGTUnQ34zivV1gVmni
            Fkjyb36LgjsaBfIP23jIRkNA1vGi1tRGonfQKPokTnfbDSTLJh052A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-06-07T19:06:28Z"
    mac: ENC[AES256_GCM,data:vwaD/e+N/n+MBcid8SaVOQD2ytPi8H1MOi5LizL0K/B5UyZcM5+tRre/n9JRG1A2Pb6fPjZb+QNTS/xfzim3hR63WQNR1whWNy7kGBkalQ0mY2mlWceEQjioDYBzKboi4QurxSdXJfrhjsJUWRdS057pUJD4ER9dae24Ysb+ZT8=,iv:0MhuMROHxpXtroagswLflmvUDEOCMcbgQGeY5JG+3VQ=,tag:/2t4d9nPM6XEC62K2uL0IQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
