---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: tektonic
    namespace: tektonic-ci
spec:
    interval: 5m0s
    url: https://github.com/pfenerty/tektonic.git
    ref:
        branch: main
