apiVersion: ENC[AES256_GCM,data:ZGA=,iv:+RjIee5chxRG8rrtkov4BeDwjt74yq2hgGlM+NChpBw=,tag:rbWv3OaAk2zwMkARKzsTbw==,type:str]
data:
    secret: ENC[AES256_GCM,data:CSHJ8iztsge5vh3Fra1RS/1UvBPfqu9t2Kg832r+ckUaiNlYGXnZ7iVa++OBbgvbpccP0b17GPP/tlXl6BlsARU1qD8sHx4JcEL3ekw0AHhCccEGYyVKYg==,iv:UbVpUurg+SyfkaLUJYwa9gthXKnZM1QOeygFMOYAD1k=,tag:bF5lHa4Bmr2ns/zMaNBUYA==,type:str]
kind: ENC[AES256_GCM,data:p31mdS0G,iv:cYQugNxkWM+Kn98lbMGmpUUyZXeht34krB8vfjEpSdA=,tag:8Od1BZtyhpZf/g/AINvasA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+8zLLiz+4H0RuXbIjCL/tPLmx4Lr,iv:1EvsLLcG19RM5epeud7DmIb0Q7ybrPvdYmRqaBpYaMU=,tag:ieqKnZ2ZrQUAd54glJ7fOw==,type:str]
    namespace: ENC[AES256_GCM,data:2EIdpjzyAT/xRoU=,iv:Aj8vNs/xe3DYPagCwSrYcoa6GJoG5nuK1uIAp62oMPc=,tag:ggAWzdQdO7X8GXB84e2Ibw==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLb1JsRGhGNFJjcHlzN1c2
              aExBRHFnUXFOV3JpWU4rZ05zWnNHUVp5SlZrCmRSRDJXNFpUUHJiVUpYMWdCSEM0
              RUkzRlVPM2p2MXF2UEp0TTV3eGdIMXcKLS0tIEoramlzYXpWMnhHZzBYVkczUCtF
              VVJxR0NHZGRtL1U1TUdySnRBMEZxdXMKqHhSaR8oF1B1gdhKFiB9ywpxOTRRo30x
              r+pwVcpp7iGeFdamx6aWINGbE2k0w819IRdYKysfLyGbCicqivF8Pg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T20:52:43Z"
    mac: ENC[AES256_GCM,data:DIjk7xTzoyrf6rmwh5DOKtfJabweiWRBI0DksT0lS87AqDeEkDiykRKmCCCd3qg0SV2xyYZoI5WXhQEmgHOncjuMuUT/v8YC6UyePOiYhguPkfcOqiPAf1gnb/yY4Ue5iQ5kMAbd+NYJErEDjrTsTgDMACFJtu6yTg+J/CtIgY4=,iv:6F09lVZkzo/q62MPt3WC5wfrqG2svpOmSaMsk/uh5CI=,tag:yJVUaFSc5VmrDJ91abf1Rw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
