apiVersion: ENC[AES256_GCM,data:O00=,iv:0Njp3pXFamxmlUHdiH3CoMyeWhWdAdg7CJg2kGK29ok=,tag:fSZTIr7mUPieHG+fJJ3pTA==,type:str]
data:
    token: ENC[AES256_GCM,data:dmdcsvUykfWSi0xyiE0Kq8B/qBufIRpy9g6rgI1Z50f9M/xalH2Q1hiJoQmD8yJ6eOtHNhdIKL+4knP0jF2k9ttNvqWQBfTCezNw80EmVzSiHbqt6vLmgwRRp7onyX0FoOp2SrWaxRoWxu1rJChutCFTjXrJ6X5JuIwxBg==,iv:K8xu2ey0wNenDPY8ITyN06J9q1/JVW1iht2ufF38Na0=,tag:De06xDzcln/LzQlDOGUxjg==,type:str]
kind: ENC[AES256_GCM,data:JOacf5ta,iv:brJC7PAw0XTV2P3fbocUwxDJBGM70jssoSl6NoA8nK4=,tag:JkxoVVjayljwsXU3egiLTw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6Jrc13CPCoF84TSW,iv:nos/fDoHK2iMSTPT+lt8nn1oUu0MOgO1fCbdtJlPF2I=,tag:/E3y8k1s8LQhanZpRe6ytQ==,type:str]
    namespace: ENC[AES256_GCM,data:wtz6mPZFX/w8ho0=,iv:TduWponjwXEk233mc2JDzxNorvkl4G6OoKNpXcFpkF8=,tag:m42G2vNKoXcLV4frxBdF0Q==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSU1oVkNkRmFWMjJJNFlI
              WERpUHlyYm5BdzVvMU1lMlVKMFFGUGxuOVcwCk00WXBrNE1ldnhKWkRuL0RDY09r
              K1ZvV2FhUTZ4bDArRnptTWlvRUhFekkKLS0tIHFVN2JPbmdXREVqWUNzdXBGVXpk
              dXRTT0RNWFlZMkYxQTZXY2E1NXdpOVEKYSvOBvo3xmfNI0VKYW8/fg2LJYsXfD3B
              Etmrifirwfffr0IV6hIp65l0Z8DnX/73InhonqCsEw5e4+HkOr8xVw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T15:12:06Z"
    mac: ENC[AES256_GCM,data:dhhow5bhsAkDzakOxiJsZz8ogeHqiXtWn5XlITrdad8EgTWoyXtgXNrjmwh5qDc1YenkuPIEq4ws/Smvpw/J756SSffD8JzUUBxMRtGLSrNDNhfHVrTBybnI3Q/H0fAGzTnHwmLYJipts/G0o8mR8zwQutgEgpyhbI4nowEW+a4=,iv:L6qlqBdydCt+dLXLwBBcG0r4Inmdmz+mXul0R2WohFM=,tag:LOZf0fF4Mik43nbZLouyLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
