apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - flux-system
    - tekton.kustomization.yaml
    - tekton-pipelines.kustomization.yaml
    - tailscale.kustomization.yaml
    - ocidex-ci.kustomization.yaml
    - tektonic-ci.kustomization.yaml
    - renovate.kustomization.yaml
