apiVersion: ENC[AES256_GCM,data:tFw=,iv:su1KArRFX4qxJar0IvvYZcbqptgzDt1p52Sicnw7l5g=,tag:UvP+nGM8caM1BaN/K44wFA==,type:str]
kind: ENC[AES256_GCM,data:kPLNCvj5,iv:NBLkDS21TtYaurXR1raQ+OYL+qzeoOvEFztn8nxq3is=,tag:9hAy3JnlO0bqdojezrnW9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NA828ZmKeZVmrKh4dQ==,iv:c8l/WFh2iwTC41sIpx441Z/m70a8+T3uKrpB4hxEjzY=,tag:a5hInbwwKyZZ8vj8gwc3kA==,type:str]
    namespace: ENC[AES256_GCM,data:pXetx/hEiJjygw==,iv:UlkwMjbCsflAmYzcACudJiJuUFp9jeAuw1EvSsf4eiI=,tag:jxkUdL6R3SIPFtZv9VgxOg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:0sn0YkG6,iv:5py8ywuNyJ4QMTiKwfUFPZCyim+A+1HDAmY1C6TOckU=,tag:hJdNgBNGDzoDvqkh44bBlQ==,type:str]
    password: ENC[AES256_GCM,data:2nmO+x6OwbN1lG3FGb1r304iD4IIh5igqv2HnpJvcQ==,iv:mxzzdVEntayKnzv4g0UwVI+N9mCRBNj6lw8yN8AQp8I=,tag:IuDxs7i0Fg+sgykXUtaS6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdVFOeCtIbTdWeUdZMEVj
            Y211amt1ZEZJOTkydkhFeUtwc3dtYlNXUnpNCkNCUlQydXlVRjBYUUpRVXU3bHRn
            NUdTMlltUkV6WEI5bzJCeDFpUHZ4VE0KLS0tIGlGb05XVk9HbUdMSm01bEVQNjIy
            NHdtbWhCK2FvYmdIRTRBL0o4ZFVqMmcK8Tjtcyg5cRssSYKrjhE2YG42Xjy+uA6+
            X2g/2N1XQ5pLdnlBhXCG+Vpo5QVX1+cx6HsTRo6FLue0woIsNOmKWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-06-07T19:06:58Z"
    mac: ENC[AES256_GCM,data:Zr3CLulGGKLCvSWosLWy/n6flYM3PCv9gLRYZqXXq/Uib6ybjkD1vs81kRlkJ3e8gJmb/AWd9E84DXsEPq6vCJGNSiMMPv0Pxc+FZwKteISRLtdBVs4XvA303WLOGOwsOwjAG7VM3+NdGyDSK4N2cH9AqQjKhZN9K4CLD4kJ/Es=,iv:H2L2XAceOOm2f5ZCp7mWj9+Oq6+QM7g8ujyXBsc1D7M=,tag:dwL4hLC3UEPHTFCe4gu3fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
