apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: zot
    namespace: flux-system
spec:
    chart:
        spec:
            chart: zot
            sourceRef:
                kind: HelmRepository
                name: zot
            version: 0.1.104
    releaseName: zot
    targetNamespace: zot
    interval: 1m0s
    values:
        service:
            type: ClusterIP
            port: 5000
        httproute:
            enabled: true
            parentRefs:
                - name: cloudflare-gateway
                  namespace: cloudflare-gateway
            hostnames:
                - oci.pfenerty.com
        mountConfig: true
        configFiles:
            config.json: |-
                {
                  "storage": {
                    "rootDirectory": "/var/lib/registry",
                    "dedupe": false,
                    "gc": true,
                    "gcDelay": "1h",
                    "gcInterval": "6h"
                  },
                  "http": {
                    "address": "0.0.0.0",
                    "port": "5000",
                    "auth": {
                      "htpasswd": {
                        "path": "/secret/htpasswd"
                      }
                    },
                    "accessControl": {
                      "adminPolicy": {
                        "users": ["patrick"],
                        "actions": ["read", "create", "update", "delete"]
                      }
                    }
                  },
                  "extensions": {
                    "events": {
                      "enable": true
                    }
                  },
                  "log": {
                    "level": "info"
                  }
                }
        mountSecret: false
        externalSecrets:
            - secretName: zot-htpasswd
              mountPath: /secret
        persistence: true
        pvc:
            create: true
            accessModes:
                - ReadWriteOnce
            storage: 50Gi
