apiVersion: ENC[AES256_GCM,data:AG4=,iv:TdYxOAeuVfw7pPXa/wcy7GgVhvfvOW2ZfNQFQTXOKiU=,tag:LnM1P4qIcez0zhVXl9ry1w==,type:str]
kind: ENC[AES256_GCM,data:qLIAH8fO,iv:MEHnGyvmM3XnfdaGT8/EHC/yIkilS9wtctSiJ6L94Co=,tag:E5/49GdgR4pc6AUHZvGayg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pS6G9cvmC44UujQB,iv:jcEpS7FfSxJAUoiXNzv+07tW4H2WD2xg2UmFJZTqnHc=,tag:Wd4RBCss5jI6m+CYgHFmIg==,type:str]
    namespace: ENC[AES256_GCM,data:1lpD,iv:qHWoyqBhJT1oeVtFzLRna7WzYrT/rS3wDSD2xueQ/r4=,tag:IkXiCHqP/1BhfT+oc55Gow==,type:str]
stringData:
    htpasswd: ENC[AES256_GCM,data:dSg8p6Ebwr7xR6t/o4B4IMRE0VxiTJauUH6B+IKfm4SP6q4PiqOA9G+7JHtd5ZWULMCB3o8qM28ZcXUyDGycfbhbv6Vl,iv:7yah/3Azz9WFsR8OKy9zcVFjtW1T2ACDRMxkiOZjRVs=,tag:MtyfjQoc7X+iWeb4iW0Sig==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUkdHVytOWXEwbXZLaERU
            d1hrM25SV1IyZy9XVlgrSTZxS2pidVlpSHlVCmthTVlKck1wM0JaS21xZ2o3UUl2
            Q1FCOXpUdXRRb3M4czgvckZ4K1E4blkKLS0tIGovL0N1VGVkb1N2d2YrT0Nma2dI
            SEp0WVNpeEF2MW5Id0wxREV3MEpWTjAK+o6y6dzdpacpvBaY+JelCpGXOZSBq664
            sJ1DK58wS8T4MU76Wf2jH9xXJGcNQxTn1CUtrwAqwpSXHdlQluIUPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T12:49:59Z"
    mac: ENC[AES256_GCM,data:nNmqPTp5HFdwoT4aWYZDOAlqc0I7EGQUMEkL77HDY/103vXk/NKf8HXStpIZUJZGxcCrGzlNKYv9uxxSJOymPoptv7x93XPU/L/agG0eORz7OuqTZKvC99ByxewsHwCeZQt4bQektaCIeIjkBgMvAxWmQykw5wusi0Osg1HRNTw=,iv:dXe5gyiKROao+wDv5hdP/vTKqZwNrYmm3WUiirdTfA8=,tag:DIVj/NONK9ZfSIixOwi7+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
