apiVersion: ENC[AES256_GCM,data:UAg=,iv:JwbTPWL9IfEGEwVrgly1gUZ+uyCkYrF+GYx9yOXIZfY=,tag:NPu5ZIAYcJKBwsnEzYm5AQ==,type:str]
data:
    secret: ENC[AES256_GCM,data:AKeJSp10GYeCz2N7HU68O4bYU6SBgktiurltBFDupnUKP78GHva6RaAZgSlR+/T1GTkCwQJQcF0kxiB1fL/AokK69XaQMMmLHNPCJCWv72VTkukIfR2oYw==,iv:1iJzjIec+SaZGui8noqTx5mqNUwuI6jJylZ9ujq9j/A=,tag:1dwDWRaau4fCd35zAxez9Q==,type:str]
kind: ENC[AES256_GCM,data:aq5A6WXp,iv:NZj6In+a8f2+5Gq3UTL7v9uAWa4cb2hNqRu4WmaXeTo=,tag:U9Y9qwash9f1AywexPJ0zw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aWniTNvpMV21Pa4u+gpAhCZkRs6g,iv:R5jypCL3Cr00xtAD/Pq0zS4AvZFJnm1G0dt7Rg1WZLU=,tag:nCaRhF8zHKH0Bq6v56JfLg==,type:str]
    namespace: ENC[AES256_GCM,data:6q1+WoDkTV753gwdeAd5LQ==,iv:ccv7BCVurGnpUbMC7S0HdOSNsB4EslQApsgSYB1iz9E=,tag:5r1Yrefw/tYeIYluO69g1g==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTGxpczhUTjV6UGhHcjJ4
            dnBXUjJmYmVMVDRIL0h6YkdNeXlwdi9vVTBFCkFkbnZqWHVPQTIvZGk4bDJNeUJa
            R1lxU25mWmdreVkxRytGaTJJV0czU1UKLS0tICsrN1N5aW81T3V6MklhVFdxRkJk
            ZUp1aDl5UDc2NFJBaGtCTG5zMFJSMGsKtJ3tgLy8oyrz6Kj5RFPZKpoIV+RjfAGy
            h9N9pX/JbLb8L6p7SgQxAjmHg1mIiPr02SzXX/FHTnk3XGv9FHpRlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T16:40:05Z"
    mac: ENC[AES256_GCM,data:4aIcLzqQnbSTo/L8Ubb6axsmExJIp0CNjs8cmLFMxQ1wqdxMFA9SpaaRjN6mw18uuprj1Av83cCtCGC074nA2Cm2WE9oGzTRowxrhh/XJOsv/2ReiUFhp2ipNjLa0rrLFZAyVfOuleu4QVB3E1agoSLubJSGm3keSSe53QlFD1M=,iv:GTP2Z26TJl7dmIYBh4VxDDwJuSo9bG1ns1a43A55q9k=,tag:AVrUaXSXP468r/P7bsiOKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
