apiVersion: ENC[AES256_GCM,data:ywM=,iv:50y/h5TXLIDTvtNC7gg9SeapX9UPlP7gpb2YAdvkSs0=,tag:SXLyz2uQicflKynR3U4I4g==,type:str]
data:
    secretToken: ENC[AES256_GCM,data:VaF9OwPIw5AXwyYfSXN+SlbBjN0oxwwUKTnR1faUHZPwMSUvNYBAIAyjPl/w+fNilk6FqZhKMHfVIBtgc2Wt0cjNnFduLBrnJAa41I4TrNM8EZKi2WyK+g==,iv:gnA0d1UZ2NgCA8EUP6iqglnU+0TibNxKMtoFnRa9OAQ=,tag:doWvb6XC/bKl6jX9ZmqQUQ==,type:str]
kind: ENC[AES256_GCM,data:rEwo0lKW,iv:St8pEZ9wnCCdU/8g3bR8mmJ1jRVrWdY6x5vcJU8X+Vc=,tag:hv7BDVcqNTHKuQGRXlRFGw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nw1NvpmMYualc9YSlLzTA3qcOIKZ,iv:ozhbjw1LXnDOnNdjzQxraSwB+sF4m/uLgl2RtxRCpVQ=,tag:YYA1Fmx+1vYfjWBVUA4mjw==,type:str]
    namespace: ENC[AES256_GCM,data:Ikbfver4w+jZ,iv:3yRnZvj0vZrfBmD2+qSZEFS5WVHxvd81GkapM8TOBbU=,tag:7KJ+m4ASwBdFjL8da+Bz9w==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzb05lRDFwVVpOSlZLa1lV
            WnF2OS9iRVNJVmUxdEpGbEVZZHJiVWpjYnlRCjU1Tzk1a0NIT2FURy9EOStuSTlq
            MnhDV2dwZm14OGtiWElnRnpDWkhUVE0KLS0tIEg1WWs5L1ZXS255b0F4bUlzU2tD
            U2JjQlNTY3Jxb2xLS0p4Z0ErVzArTUUKbNQ5MGn8xoCVzxGmFGaxZwiTmZ5CYKke
            fwvKfit3HWquvlOdqllzR4/hWNJLNVGEfG/KhX5ygoufjGRZsETbKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T16:34:09Z"
    mac: ENC[AES256_GCM,data:HEwlgRdZiwShmqMnumSot2lH7mLJNZ11j2lvjzms3PccO2vVsaorxApi0cTUX4J9WDVf7mKMa31r/wJMLHAok1ji3PFJHCBeEh2Zm9isJepdDmA5d3IK48cTO3bVmJ+qKLBZTK6eKb0zdvP/wTxhsfajklw83vpT++YOnxUtdYE=,iv:fC+5z4fhKOx4pNQRVirLn7yz2ZfnvDk/Hz/rTiMPURw=,tag:nncpAaq45xqG1L+2AGgURA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
