apiVersion: ENC[AES256_GCM,data:zls=,iv:MGhZmeCzmWhQtCnzpdN1vJ3QyADQc8Vc73zTDngb0CA=,tag:j13oYs7qzASJs+Q4QHsaAg==,type:str]
data:
    secretToken: ENC[AES256_GCM,data:RVd2rrgAqvDR6GXi973dkHS5BbXwhEsUcO/jNRp0rbFja5/NyY413pQsUDdjYNotFkx3fx2cppzXucOnkp3bo4WWMX73znFpa1n0Y65es4C1V95Fkt4PMw==,iv:9U+9xh1waL/ENX7tZXAzBJdPVZ56bkrFsJ8zMiQWcaQ=,tag:PoBu1aqWKAA2zeLkppyFOA==,type:str]
kind: ENC[AES256_GCM,data:Ad0y91O6,iv:Mbeu/teMJf7S+hcyNqzKA+H6mJL8x1mnYVcJ7SqV82k=,tag:WkMOpne6MwqMdPQq65PEgQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KlJkbox1r7v0QvJH7c0od2TjFo6d,iv:GswF1JQxuLH++yJ+g1ctNR6QAMky+JiVRKH024yC5lw=,tag:zSNAHWPjwmBHDGmkSNG9Ig==,type:str]
    namespace: ENC[AES256_GCM,data:2BMEux/P89hlrxmNbnQDCw==,iv:qaa4v4r59sASp1X7VETHrRvvnKh4Mpq8pauFHL08rwU=,tag:U+nvZVdD8YuDZTelRgvmhw==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQnEzOWVsRDcwY1V2WDhH
            WGZqZEo3YUxONEdGOXRHT25qc3RJTldFTlFRCkxPU2pQd2YvVjUvNG5wSVppTVR6
            citaNTVudFhGdXRITHg4eVFoVDNiZGcKLS0tIGRTQmhMVjNodWhCMVZSS084dzZN
            QjlXc2VURXpKTms2bC9kcWVEZC9iQ1kKNFtF5wQmCClvihQhNrxn7s1xb035XfXF
            wf79Uk78qg+Z3A6H5sLXpMJWmeWebWHHCVJFjQb30O6V5KesSspD8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T00:55:19Z"
    mac: ENC[AES256_GCM,data:cWy4Qu3Kf5DJvZsZt3XaHERTgTGwzYYblgNr5wD+zBUGlX5O8LwKPH4z6iClyd1P50o1qem3IsgLGdHyEDi7n4C89B9HQby0VgFU4lUOtx6frfEDWz305VXrmpAWYJy1rnn/W58yjE/gfqL9MT2aXHfzaFLfKzdcV0+haZ1b298=,iv:pm0EeyIAQ35R47KZW3TvaZHZHWxLczn2FykHzCltihg=,tag:zcfEfNxh8B2/QDEMbrT6ug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
