apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ocidex-pull-request
  namespace: ocidex-ci
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: project-name
      type: string
    - description: path to root of the app (should contain go.mod, go.sum files)
      name: app-root
      type: string
    - description: path under app-root to target for build
      name: build-path
      type: string
  tasks:
    - name: clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: Task
        name: ocidex-git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: log-git-state
      runAfter:
        - clone
      taskRef:
        kind: Task
        name: ocidex-git-log
      workspaces:
        - name: workspace
          workspace: workspace
  workspaces:
    - name: workspace
