apiVersion: v1
kind: Secret
metadata:
    name: ghcr-docker-config
    namespace: apko-cicd-ci
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: |
        {
          "auths": {
            "ghcr.io": {
              "username": "pfenerty",
              "password": "REPLACE_WITH_GHCR_PAT",
              "auth": "REPLACE_WITH_BASE64_pfenerty_colon_GHCR_PAT"
            }
          }
        }
