apiVersion: ENC[AES256_GCM,data:8K8=,iv:mG3fdz8l5hx7n2StZcVWilyMCuHC+hNV2ItVO67ptYg=,tag:yd1nUR3d937t8KjIQzIYNA==,type:str]
kind: ENC[AES256_GCM,data:OsBPguRQ,iv:LZ//9GDKiMdvqsWOw/nJqEfS+T0I/00Vt7JoYNDezDM=,tag:mh3DVbdf/dvSiGl6nVDE9g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tVBC57PXTEdKDocLpQn9E/5zQesq,iv:5VJGllhN3tnOojotjmvdSFsYQ4pQ2lYdRPXjY/gAEtM=,tag:fFOjRO3cliRZtcNs0xdt3g==,type:str]
    namespace: ENC[AES256_GCM,data:qZneOty8lHYdP8U3,iv:ggW87OGbMFRTmq4QlyoHvGhcDU5PodkuibHgNzCYPYk=,tag:lnttbb9F0XKR0NQ7miX/bw==,type:str]
type: ENC[AES256_GCM,data:ygWxqbWr,iv:diqvj6OiH1b0bwsN7fwnsQnno37GtrwVRHVZJieifJs=,tag:OH6RiuHPEvVTBu7vwCnK3A==,type:str]
stringData:
    token: ENC[AES256_GCM,data:9ZtNJFAoBrFCFN5+w51qtpF7kVnI82LNiPk9fc8TfH5oDD/3JQaR0YAiHN+Ago+Ys5VwfSUgAwIGFIbdPAFI/gVffXmr5O2Tq/ESnLVJkwIwEjM0L72LNsaGVxxm,iv:tnkOYklVX/NtoFxyXG1fTM+5/hhAy32NEHM1zYEgnQY=,tag:Qpw4fQUBkiDUjtg3b1IMsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ01scUtycmIwVjE4WFcz
            Nk9VcGdDKzB3dFJtTEovN2FFNGdvcFR3MVQ4CkJvSVpMMUtlRkluV3ZOTlRyemh1
            UkZkcHdYbDVnOVhHZUUvMHNRUzN1b0UKLS0tIEdIRXVhY3V5NW5ZTjNFUXRORHNI
            bVJBRkdlZFU2U0hWSHM5aU0zR1lmVmsKeqp30CckhY+v1FEtfFnWv8vlw1oN2m0g
            zDU5ogw06z3cjfMNElhxZmRUzbLZdxZd+jwlIr8d+w6F/roGSiV85Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-06-22T19:06:37Z"
    mac: ENC[AES256_GCM,data:2e57RWFc3ulDSQxNOK60JuQ7d7ixZ2vFUErAZ5HI0g+R+F4wZIXiIlzklLmLrRjpbMRCeEbkJLc3PwTfnzrURn4OElBN42jV6u1EJ6nwTSDFlIwbudSmYhvdodo+Ronnrmp7fPZktmMJFQ+njc4dLlhly9B8TYDyS4UEQQNs7PA=,iv:17hTuc3t4eBwESt1WuK6KDTbvCJZoAUf5r5R5HaiXTg=,tag:nGHWxA+nfFC45jtqodO9ig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
