apiVersion: ENC[AES256_GCM,data:px4=,iv:MfvCa9S1zErkIoXh8VQm8Gs5/xbWmT4vJn1ok0Hh5DQ=,tag:obv9r6kEDGLESMsr5pN+fw==,type:str]
kind: ENC[AES256_GCM,data:xEIHSGkS,iv:kbJEyNzQBrmxV/9DGefq+5ffPBAb8vgZKWQYuXH6WpY=,tag:t/pMMvjLzyG1cel1yU0WiA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WQs/eZkRgdlgcl7D6q1Va7yVyggwZQ==,iv:ylEQtkSdjrDkzxhTGRbk/1JyTqyTBI+6BXkNO/AzoWg=,tag:XA1xp9daJGrZ85XY/iLSFw==,type:str]
    namespace: ENC[AES256_GCM,data:UEPherkOvgb+EBzj,iv:PsT3nxwb+Ocn5QkbZ12urvxab7X+B0ClJJs4a5xbceI=,tag:a/M+jOS96hP5LCNoOiDbkA==,type:str]
type: ENC[AES256_GCM,data:AB6/Y/5U,iv:+oBLYtWZzAgFrpoHGqEE84ymx0eAAAa6bYmmbuSQQRg=,tag:ogvtbYGqppdP2dQ7xnC5Lw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:zjVFmZG3l6S6QwxyiACEPriK/vMgB43AeGtdZWSL5dj6aHksWANQcg==,iv:897pXcjSEsatgoQ9JsWccJ2U8gVupy3KeEEjVX9uZms=,tag:8GkMSiBRXI1uvFcMR+oyUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc3E0aHBaMXo1dEJTY2Rx
            WDQyVlpjeXFMRytML09aRzZKWDZiK3pQaFF3Ck5DbVdBSUdCVnJEOTZKZzVvNmw3
            Q2d1SDRJZUZXbHJncTJjU1NOYXo1RFkKLS0tIEhKRmh6czBqN3MwSVhrQmo1bVQw
            eFYzUTllSkpEVFVJRGhXdkYxanBQcHMKxyP3j5sqFRI/8KEaqkqBgzXfmxmEAfIQ
            jvVzmvIwqRTJwMlKL2gCsvtiKWwA7YO6rULLulIErhCnSjvfbkur2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-07-24T15:23:37Z"
    mac: ENC[AES256_GCM,data:vr12CS76LXsHxkMFCSbWlQIevgiqZ4FSCNFMUUKWuS+2E7BelyjpfdRowJePH5sACCIIHsjdeQ02idnPFwDwNMKjSGnhG2Y9LPA/dXVOFnafCyi70DTcwlwghtCQJZHEgUPqW3C1b7AzzOny0gdW14oDQt2ot4nUU8OYf4kftqY=,iv:fltyBZuTzj/SSkC5m3/NP11WUySWhe4S9hX6CB0SAqs=,tag:AjlTc+fDU460y5aUGxXtzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
