apiVersion: ENC[AES256_GCM,data:/hw=,iv:jGrSyKdhuki1ETKZiAc+twuppRQCdhD7LlDIzipVac8=,tag:XgY+1efM5tyAssy9u/zxbg==,type:str]
kind: ENC[AES256_GCM,data:T3nxBtu5,iv:pvR84sTjamBqxxyDwaQ+UWeZ9ZuXNT6fSoa1hWcP5Cs=,tag:E1xS1CQrmFIpptJcRYpuOg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GPhBBYyWPMpcpDO6tzhyVLNVtdDt,iv:lGi9T/LQftw/HmNDw0yykWSXLvDnz5P4a0wMo2l8HsU=,tag:0YI0rvpTCQLepm2uPBwTbg==,type:str]
    namespace: ENC[AES256_GCM,data:RaiA8en5GXVqQrlu,iv:RPb0zLuG/uRMgIGJcvyF7XYxddO4dC3O2SYwPHtenOE=,tag:tWNJ2J5jI+1sE9XzluGmxw==,type:str]
type: ENC[AES256_GCM,data:RzAsdAnx,iv:QEg3bwGnK+0apkyjEdjUhfQV31KDeqyQksd4FJ+CY1U=,tag:gpmSwy7UNu5mMvQTSFGZMw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:MKFa6dMa+PIVBZeIYFMCWJ6dtEJS6lpd4MeI1crxIthKJyo4p5MVfsvDfK38Gp1KyVOZwKsplHAPveaaiqyzIu6P3LjpHv3ehvlbf0JXNtvNN2kCXdInB1Yj4nEr,iv:b4KNSs7dH06y+eYptKljuCDNAmszUtdqMPF7NaZ30co=,tag:4rnz1a6LEqWt5i9CdnczLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSm16QlE0L0JRcStkSU5y
            U0lWYjFybFd4ZU00MmY2WXBTY3hoT1h5LzE0CmZ5WGhhSzY1cEc3QjVmZkI5bEhC
            VzlNNEVwSzJxdEFPTW5IRDZiV2c3MGsKLS0tIHpUbk1TZ0ZXRi9JWDFpMzVPSVVE
            bHBiNjdkajBZajNKYTlzQjZucUh6eXMKgO2mkXrFITpF4PB+XCgx3eqyw1SXu5Kd
            YY2sDQVqrfrKyiA8zg4fRdM6iQrKACks7HPL1VSyxjVxOsh4AR5Vpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-09-25T01:00:14Z"
    mac: ENC[AES256_GCM,data:wHhrCXiv8wD+zfenC33mQcNPG1I6tZPF3Qos8gZwvD2kUvIek9YULKaJl++QzHhAleOFgH3NRsaPpb4eA0G+K21sDwAO7VgYLj0r9/u1NPwbcNvG4QcBqNUwwm1E2uD7hZ7qtbXhTj3zsuu3VbT7+zXdDhp92+xO+E9ExBeJes4=,iv:zs/6EWUR/2QX0qq4tidpwaP1bOqsvuDNlXsDMSZZoEg=,tag:FirKmq1ll2bhZicCDtYVfA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
