apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
    name: apko-cicd
    namespace: apko-cicd-ci
spec:
    url: https://github.com/pfenerty/apko-cicd
    git_provider:
        type: github
        secret:
            name: pac-github-token
            key: token
        webhook_secret:
            name: github-webhook-secret
            key: secret
