# hosts/server/default.nix — Main configuration for the server.
#
# This file ties everything together by importing all modules.
# Think of it as the table of contents for this machine's configuration.
{ ... }:
{
  imports = [
    # Machine-specific hardware (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Modules — each file configures one aspect of the system
    ../../modules/nix-settings.nix
    ../../modules/hardware/nvidia.nix
    ../../modules/networking.nix
    ../../modules/openssh.nix
    ../../modules/packages.nix
    ../../modules/security.nix
    ../../modules/users.nix
    ../../modules/zed-remote.nix
    ../../modules/claude-code.nix
  ];

  # Boot loader — systemd-boot is the standard for modern UEFI systems.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Set your timezone. Find yours with: timedatectl list-timezones
  time.timeZone = "Asia/Tokyo";

  # stateVersion tells NixOS which default settings to use for backward
  # compatibility. Set this to the NixOS version you INSTALL with, then
  # NEVER change it — even when upgrading. It does NOT control which
  # version of NixOS you're running. That's determined by your nixpkgs input.
  system.stateVersion = "25.05";
}
