apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - cilium.kustomization.yaml
  - gateway-api.kustomization.yaml
  - metrics-server.kustomization.yaml
  - local-path-provisioner.kustomization.yaml
  - cnpg.kustomization.yaml
  - keda.kustomization.yaml
  - tekton.kustomization.yaml
  - pac.kustomization.yaml
  - tailscale.kustomization.yaml
  - hubble.kustomization.yaml
  - cloudflare-gateway.kustomization.yaml
  # - podinfo.kustomization.yaml
  - renovate.kustomization.yaml
  - ocidex-ci.kustomization.yaml
  - apko-cicd.kustomization.yaml
  - nfs.kustomization.yaml
  # - zot.kustomization.yaml
  - ocidex-prod-infra.kustomization.yaml
  - ocidex-prod-main.kustomization.yaml
  - ocidex-prod-operator.kustomization.yaml
  - ocidex-prod-registries.kustomization.yaml
  - ocidex-dev-infra.kustomization.yaml
  - ocidex-dev-main.kustomization.yaml
  - ocidex-dev-operator.kustomization.yaml
  - ocidex-dev-registries.kustomization.yaml
  - dev-spaces.kustomization.yaml
  - monitoring.kustomization.yaml
  - monitoring-extras.kustomization.yaml
  - trek.kustomization.yaml
