apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  dependsOn:
    - name: tailscale
    - name: nfs-subdir-provisioner
  interval: 10m0s
  path: ./talos-cluster/flux/apps/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: prometheus-kps-prometheus
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: monitoring-grafana
      namespace: monitoring
