apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - release.yaml
    - tailscale-ingress.yaml
    - pipelines-as-code-secret.enc.yaml
    - tektonic-ci-controller.yaml
    - tektonic-ci-ingress.yaml
    - tektonic-ci-secret.enc.yaml
