apiVersion: v1
kind: Secret
metadata:
    name: pipelines-as-code-secret
    namespace: pipelines-as-code
type: Opaque
stringData:
    github-application-id: "REPLACE_WITH_APP_ID"
    github-private-key: |
        -----BEGIN RSA PRIVATE KEY-----
        REPLACE_WITH_PRIVATE_KEY_PEM_CONTENTS
        -----END RSA PRIVATE KEY-----
    webhook.secret: "REPLACE_WITH_WEBHOOK_SECRET"
