apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: homelab-secret-scan
  namespace: homelab-ci
spec:
  stepTemplate:
    computeResources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    workingDir: $(workspaces.workspace.path)
  steps:
    - args:
        - dir
        - "."
        - --config
        - .gitleaks.toml
        - --no-banner
        - --redact
        - --exit-code
        - "1"
      command:
        - gitleaks
      image: ghcr.io/gitleaks/gitleaks:v8.30.1
      name: gitleaks
  workspaces:
    - name: workspace
