apiVersion: ENC[AES256_GCM,data:Ck4=,iv:YpZdp7a5d+vbqu4FEGuVfB/ebXIGbjSwSfkmLe7yfPw=,tag:IqNRDzQw6QvvM15OoR5nGQ==,type:str]
kind: ENC[AES256_GCM,data:3yXRb53Z,iv:Xt7NU8CGfu1kl+Xh1bfsqsOUyzTScyi36eYkMbExHUA=,tag:DqNnTvygr5eJ7hhRGDkxkA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:c2H7sD2NCJgjJwZVNuEd/sAd85TuiIKj5nyI9w==,iv:FJjts/a9kRrw5hjxGGw+802FgMJxvqnkS/nJul/WyCI=,tag:yQpFNbDkVuWRQtL5jpBcew==,type:str]
    namespace: ENC[AES256_GCM,data:RHRUQRGA8SJmcY93f+wFXUqrqB4=,iv:m+v6RznrcThaqkmZbNKfiEfMgxKLEZu0sIVCZvD2YJg=,tag:Nk/9sUq3QpCzOHkeYF9IMg==,type:str]
stringData:
    OCIDEX_API_KEY: ENC[AES256_GCM,data:4BaoHggvAsefZyp8gqxYio7BYAkDql55+Sz7+bsYzqyLK/03UwfKkUZe2ejLwPlY1mo=,iv:OUwGI7oNEGFuy14HhXLBUee3CnOYjygMrPQHuZqIn48=,tag:48Y4h5/lM7ySC7X77/tpSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSnVDZUR5aGNISHBEZzVn
            NlNEOVcxOGJVYytjbSsvdFRNT1FmL2xkQkFVCkF5dE91cFZwZG5RTmRFUXhIZW1p
            RFVnTUw4aGhqVGZwMHM3NVpUbXZ0ZWsKLS0tIHgyM3RmTFI5bjZIcUl3R0Rybitv
            MllENVUxZTVuMnNhL0kxd0VzUFMzYkEKU6lDkWSZ85wUjO4YPKro1UKcGpzeGeTF
            5oTshhkM0htfRR6R+WNoFeW2abhbg+uHMkfDChQO6MZsATicBhfN7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-08-18T20:35:08Z"
    mac: ENC[AES256_GCM,data:SFhwahGR0DtlrV35QRJsAT5cVdfXsy2snFEm4sODo9VYPnFosyDUSboQLW399KoN4zUI/nlRJ2B/yGIfiSnFRzhMdtcOlhhuN7KUv8FC0GGPh9F8ESoWMCJARKeRH6LQBUOdsnAkdpJj2qPBIClEaMvvSGexu6FYfPILribjoYA=,iv:roNihvdh4bFyj/fo/FAz+wmZiJRcgbUaSiAzg3ln6FA=,tag:oyDGM9YT587w5MM4gafPYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
