---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: ocidex
    namespace: ocidex-ci
spec:
    interval: 5m0s
    url: https://github.com/pfenerty/ocidex.git
    ref:
        branch: main
