apiVersion: ENC[AES256_GCM,data:wbg=,iv:nMllFOMGhj3fdqs7qJog8LItPzU1oNijiCaWiHfOt4I=,tag:lV/t4pI6NJSUjpcbDifeAA==,type:str]
data:
    secret: ENC[AES256_GCM,data:uGpcJyKJbqovDKcpoCRErmdy/6vfwyhnROlQ79iRAQgtJanWKcvH2VeqMDNANRgDh76TnztUruS0SjY+R4V0kYu3IulEHihdJZyI4YaUbW73zmYXRqLjiA==,iv:NNX01xr440yPydza8QF2BbVZwag8H0X/lGRm4Z00gdQ=,tag:7eN0q4vj8hAHXpzA1z6PTA==,type:str]
kind: ENC[AES256_GCM,data:Sden+8ta,iv:0O8exltCIWmXkesXwLpBlfjfEOmqOrW8oD/0yFx9jGU=,tag:Iwl7qO23Ly65x1EvNWKm+A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8xkWXYyCQ9IC3HdcZx/hRjOuGLg+,iv:hj9sdBv18HDWP9fnrAeILrhYs/mhpEuiJcsrzEVvEdI=,tag:cVjxnQf3ziSb5qWjzDqxEg==,type:str]
    namespace: ENC[AES256_GCM,data:drmJYwwu9W8V,iv:q9WmDseTTozSGlVv2mi2IjocqZ0J938hSuoKjMcmuXE=,tag:ZC07CQ47q9P7M12UJVSKfg==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxM2cxRDFXQ0YwZFZQSlp0
            QlIzWnpiTnFFOFhrS0dKS05FdXBvNkt0SFZ3Cm9KZldFMjJ5S1BLdnZuaUlTTnA4
            UVkzOVpseThwdjMrNENHblB0ZDRRaUkKLS0tIGFtNTJlaVRGK0c3UVdQSmJPMHFa
            VG0xTThEci8xejBvVUtTVTR0aU10NFEKtA8mwYNpELaVfZOyh4t+eFwov4kx9o5U
            86GolYD4d20eWnx3f3IE/xVXB6kAb4Tp4QWshLNn9IFgOSqLQHkM4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T16:46:55Z"
    mac: ENC[AES256_GCM,data:FTZvnWfRL9ANzeLQfcLy9UEJcKg9ZBF8eEzDD/qOz+VbhAfspszaWYnKR8+9i4DskpkvfkNlG7r9Khi2hI26DVnKIMmDRY6z5CVAEFLZeFNXQg1hPB1awjUbuxzRaUIuMfxBm+MSaowGw8gpt1/0G8OJ6Y1Lj2ipXwrUzb8HFDw=,iv:DdNtLvP/sbRlgkyfmv6ZMwYWlmpFm/pH17t8WtUREb0=,tag:WG03yMJCdfl922az3L8lUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
