apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: [keda]
  selector:
    matchLabels:
      app: keda-operator
  endpoints:
    - port: metrics
      path: /metrics
