apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: [keda]
  selector:
    matchLabels:
      app.kubernetes.io/name: keda-operator
  endpoints:
    - port: metricsservice
      path: /metrics
