apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: tektonic-build-npm
  namespace: tektonic-ci
spec:
  params:
    - default: ./
      name: build-path
      type: string
  stepTemplate:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
  steps:
    - command:
        - sh
        - -c
        - npm run build
      image: node:22-alpine
      name: build
      workingDir: $(workspaces.workspace.path)/$(params.build-path)
  workspaces:
    - name: workspace
