---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: ocidex-app
    namespace: flux-system
spec:
    interval: 10m0s
    path: ./overlays/prod
    prune: true
    targetNamespace: ocidex
    sourceRef:
        kind: OCIRepository
        name: ocidex-manifests
