---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: ocidex
    namespace: flux-system
spec:
    type: oci
    url: oci://ghcr.io/pfenerty/charts
    interval: 5m
