apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - oci.source.yaml
    - flux-kustomization.yaml
    - httproute.yaml
    - secrets.enc.yaml
    - postgres-app-secret.enc.yaml
    - postgres.yaml
