---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
    name: ocidex-manifests
    namespace: flux-system
spec:
    interval: 1m
    url: oci://ghcr.io/pfenerty/ocidex-manifests
    ref:
        tag: main
    provider: generic
