apiVersion: ENC[AES256_GCM,data:3MU=,iv:4cr6oxDERBwg1AtcRIII21aQtWc2PQC2g/HoGEugzoI=,tag:PANx6FmaQqD1vdvVOqb/kg==,type:str]
kind: ENC[AES256_GCM,data:Xni5CJLH,iv:vK2SFnakYpmTDhjhkF7ilwWcDouN8UI98sIraLfbfkQ=,tag:vg/dtjsR70syuTXA7CVPxA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:1Xx5truVmd8I46aesw==,iv:42p7uW6KY2Jlym9JjSbbTaXB0HuUp5ryWbJDy0+Nh5Y=,tag:Yh+DbOw8ZDOC/DT1+vskew==,type:str]
  namespace: ENC[AES256_GCM,data:MNr2MxDv,iv:OWDr7pa8Mg2/j+UgNxz3T/3OyclKpDtdx8fSqDrkmz8=,tag:7wAS3G31flq+kEBai1xuew==,type:str]
stringData:
  username: ENC[AES256_GCM,data:25Oe5pkY,iv:VfVeToo82k4pUNpflca0gqKf2BiZ5euW3oOnwnW0djQ=,tag:7C7prCNzd9mN4dLwBgdkxA==,type:str]
  password: ENC[AES256_GCM,data:HFlKvmLfrL+sZOLOv+5Bcg+gdmZpcj15hvKSbC6EwgI=,iv:EdaYQB9irBQLsy6AtpWROEwJFkUyjZF+6wfMDP3U648=,tag:dds4lEc3PjJuZLgKYpzsuQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQW1nQzhqay8wYnBpUmVS
        cjlRempVRk53eWxpMzVYSXAxL3RiMm1HYjA0Cm45WFIvME13VnFqK3VWRDE2US9o
        L05nSzF6cFZmYnZCckxBRWl4dGluYmcKLS0tIEFHSE5ZRGFiVjV2QzB3WjdDVEVt
        QU1IMnhYTm5ydjk0aTJQVklQVVBraVEKXjdnGMi2rveaFovPGCjwqSxAV8ifr9yE
        cAsHiOVN05W3wfXQVym513Hz5gLDKME5HBfjOTbIfelePZ8zvnsOkQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
  lastmodified: "2026-05-31T16:50:01Z"
  mac: ENC[AES256_GCM,data:ykE5TsvtZalwClJTGvw1tqojkyIOgu3zWn2FXMfJTcZ4fLiy3vQ7Ko4SqYM3at32+I6BpraHwUQhf5Hqnuprh0Vl9QDqa1Q34GUZeh6gnX9OMTS/3dugz46+7d/jsSxdm1BME7Vf5NlFtat4996cc5k9K1Bz+vO8Bwu1tD3Pt18=,iv:nlDCEv1w3d95wzeuUSPMCNDu+yCSLKDv20ECWP8//n0=,tag:SJK9sPgmrncuWlJUYfUEIA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
