apiVersion: v1
kind: Secret
metadata:
    name: ocidex-secrets
    namespace: ocidex
stringData:
    GITHUB_CLIENT_ID: <github_client_id>
    GITHUB_CLIENT_SECRET: <github_client_secret>
    SESSION_SECRET: <session_secret>
    POSTGRES_USER: ocidex
    POSTGRES_PASSWORD: <postgres_password>
    POSTGRES_DB: ocidex
    DATABASE_URL: postgres://ocidex:@postgres:5432/ocidex?sslmode=disable
