apiVersion: ENC[AES256_GCM,data:qlU=,iv:2wt67Mm9Xima23RWNxZHlY2qCGxV0i1YIsaPMExwWBY=,tag:KcgyPRcvVDxvcsOG3uDAAQ==,type:str]
kind: ENC[AES256_GCM,data:dqrba77o,iv:Pi8DfszZ5IOyt4grBeBCkwKWxDA9IwwWywLQ5xRDOYw=,tag:2XEqXp6HvVXHq0hu0g4oSA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:sk55Bj9YzMCrgBo+qAI=,iv:M/wnK302GKMNItvFNnglmxjJj/2eOxO/f+EE1rzsS9Y=,tag:5i3NyR5FFqoE8fUfbyxxpw==,type:str]
  namespace: ENC[AES256_GCM,data:6o24YnnF,iv:oLT1xtSJmARk0BM+76towrkWGfb+OxP2tNofjuIky3o=,tag:gLm1i7yRsi//WS5QjlGtTw==,type:str]
stringData:
  GITHUB_CLIENT_ID: ENC[AES256_GCM,data:Kdncb5KbLj3G12aFDnIxtgiu7V4=,iv:Oayd1FtWUXSoyZHIKapD7IszhQqpoXpfUAqFw2XQl8M=,tag:uB5/2YegtKZWikZi4WG6Og==,type:str]
  GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:vMOSN8WgvwgQJlRBMZiAinhHkuFhkUVG3t261F48Vc5rE8nYuK9JdQ==,iv:4jtoDnB6OEwbnFhV8cesgsqxrH+jNlfgAMxiukY0LgQ=,tag:hpQ7Bce80RBYcSNUma7NuQ==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:zqVjeIugU2kzhb0F9vDDy6y1VTVdW4Na2qzMh1yR4jUHj5E0xR2DmX6paDTgy/sGYP9FHoanRHHEAXfbufvDIQ==,iv:57vVUCeCgh9F7t1/36PGwI7+FVeb+tK0CtMqQKt+hBE=,tag:jrhsIxXYglAWVqLMQ/uHig==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:sSxAukRX,iv:krhxOe0pp13Uj4LSUf/czHy3JhnwRrxDQJ0fygSyUqQ=,tag:FZs6iWnjWHJXTkzZg9uGog==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:5NVYxTUfVsY8JrqE6PdrSIQ+1UZLACTVZIxl8cbbZ7A=,iv:gtcIyhDAVwEMzF0mSp/p+4PYn6dtfPWHyCdztKoLYDc=,tag:BndS6RItv8cbvNbGEeepNA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:nXwCucyq,iv:IN7IasHAw7tvGHugdV3hEIVt8lLQYfyIeEh4+H9qhkc=,tag:bYGJLK9K4p2/WrNEzNIf/g==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:kLURKBK/GQ41RLy4QC/cBwQTzxa3VQyKzUOoqx+YRUsjlR+ixk08SvMZsXwOfJ2gfC0f4y4T+5f86M/O0/VZK3L3K7hwG4l2kFO6miJfSd5k5zt4/GOWcuz8Fhqd5Ck2bwMefE9TfUhoeezGM/c8+cCzHdw+98+VlFsnCQb6K84xJvuVCmGgBg==,iv:zPF4fUrFa/fzJ0KTBA16K2HENk9Ra1ZNd6TFW4Xnp+A=,tag:BMmFPdOvW/0WF2qYotyjag==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVld6VmRGQ2x3UURoenZP
        VzREaFBYbzhiYXlZTklraHdGZzQvMC81a1JjCnJvU01ObkY0SHlGWEU4K3h0M2R6
        L0s1N3o1ZFZqSnYwb1Z0THN0UHJKemcKLS0tIC82RTlwRk1FUVpYOU5ibndueFhC
        OUVMUE4vVjRrSENKOUQ5WlBkbURZSXMKPf3PkiFk5dosmqfwT8Y7pu3U/rZi1OSo
        JGKzOX0XUy1RSLJ1dXvY8XTVEjitvxUZUo7f1Gmf4oblTrtrwIwS7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
  lastmodified: "2026-05-31T18:17:46Z"
  mac: ENC[AES256_GCM,data:7rpQEGfM7Gyx/a5O9/I1Uidiy9XLQ6ChXehMKPdXkUV+GhNt4YSxw8Dg4YEAg2zKSR7xEAvGNuCJqxMSXVm1FJm+J/sTzfyvo9CgUUVxVj1joZge1pFJkk5QNcwXC/YywoVoW+aBN41XmxBwPqlzAZtZDySc0yHwQt4w/i6r7W8=,iv:bYeHW1HFXblv8GsfBJ1vLoJrBNYO9aTpPCnfQmNHycI=,tag:jGzLboCtmBQvEW5BQCHTtQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
