apiVersion: ENC[AES256_GCM,data:5dc=,iv:ahb7avCwpvH4a+Vbf9wqlfUMjOK7i9Wm4CIAHLWW+ZA=,tag:QELVttgicsazih1U2fRJzQ==,type:str]
kind: ENC[AES256_GCM,data:CvhuwKaZ,iv:YhyhCOFCzOmE0X6OKh14XoKjnRIyXMNg2gOWRDDmpl4=,tag:nLVnpQL91GEg0P4Geog5FQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:80+iKTbtw7TzHCJ101Y=,iv:aFX2k8bofBRfR4TTNZQ024uqN5llncMayJKlK2+RaXU=,tag:lKzvYCi778Ku4PM7pCm1MQ==,type:str]
    namespace: ENC[AES256_GCM,data:R6aPsRl8,iv:P3HQk9EFKdjC6p7a/gVO/sjzPVdz9TPYvro/XVl6ybM=,tag:GXImllGukdYwfGzO9UtWDg==,type:str]
stringData:
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:wYUgEnpaBEi+BvnW2BRgOAJ0zjA=,iv:msy4dTGSMcOElv0vz8nETrG/TxRw/DVSKHRWqXdX2dY=,tag:t+Cfez6WjmV0IdPTQ/mkuw==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:JDWXeOvuLdyvKZRG4+3gXzE0ogx7behWPzhH61I+ai+csZuCbaZ0VQ==,iv:5+sRfdLfJwbYtfn94fDJ/QrSsYl5c3G2K/KdDVg8CrM=,tag:VIG/9ZWjgeXZ3+gJyPQr6A==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:fpOBmLwjUW26cT7zCclsV8xh91i1nIVJOV8lnQTMnqPL+nM4FEJCdLwuUrNYMlW0YcUByOUW+Hi77xlqUa6CXQ==,iv:sRExSeCR825VyUpBODYB6qD+Mr4lVLBL93lUDhvLHL8=,tag:dRhBvDFjH/pajcJVPdxogg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:jg1TunbZ,iv:fC1+AwO8R4Wl8pmSsIaXE/+PixrqLEt+17UmMoLcBZ8=,tag:e9esgZKNVFdd93yM1uDMRw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:DzuVRN2Ooj1vZr7nY+GuexnQxqywLt+YxwPShmKX4KI=,iv:wHef1rVWclZ/KwbmRSt6+3Wqjo+VEO34zjl1TwBmndY=,tag:84u5vzoGMOodYZM/oRrzzA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:3pfC8kcK,iv:U+CL8xAs08pvM0ESkYKLvTk7Q2QckMzahviZqn2kL7c=,tag:telJ+GtxH0QvWGV96+OXMA==,type:str]
    #ENC[AES256_GCM,data:oPBszYRS0wgZhXRKd1OE9TcAKhJR4TrPFK9qCVgWTQlQriMDlVcXWFekqNhoqMKfz16hnafb2n0E3bwni4BJj/1vfSbz73ZrFMdr1Q==,iv:jWW7N4jO2zd7SsdiWWl/zxa0fzbr3i3jmOj1XZqi0Rw=,tag:PER7C6/KfXmmFtFZj+9jEQ==,type:comment]
    #ENC[AES256_GCM,data:hZl3c2Smx0+7vZXt6Q6nsVUnkB2Pn4Rr1QySo6GIFiLu4coNU7vX8xlShXGHnVBCPYaEMF7XY3t75CcQizKc7FBsSbjpxxzgP/aYgw18D1rL,iv:K9HDV/MaidI52v0u+z9zDgRYXfB5HudG64nlAn3zzVg=,tag:q/WT1LB43VhasDYq5A1gLg==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data://iqBS2tAoU1KsjCV2eqVyKFk+NyR4H7PyTSalmELFuaX/IMUfwPeo43RoJqD0JPK8/9qYewYojqLidoW4ObDzs/B9x0nT68T05TCflSVBPborocxxZ3auysm9a4jVJb1s9oGTWim7rsDl2Xn77z,iv:uqCpXdfavez2FT5sIELEbhrOIUfVksaFNhxS++ODctk=,tag:NLDb4B9sh8QOij8FtgMEdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcGd5dkhMeWpLMXBkQVRi
            SDBtdGFJOGVyQW82SDR6QXlyQ25mck9HOHdzCjFlOHFMMVdWMU9tR1c5RjJiV2Vj
            VG1hNE9adTZnNlc1alY2NEloc3lTU3cKLS0tIGk0eWcxRE1XYlhGdzlQWFVjejNM
            MjFVS3M3Mlc5dktkdnY0Ym1TZEN5VkEKqPPtBOTOF7ygX1cEuchepJ0ndmU/sRcn
            vYsQSTehXM7tlsjEme3Jj/qWjsBIfH4hig20Ds3ZHW8MY/Nz8rudRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-05-31T17:35:48Z"
    mac: ENC[AES256_GCM,data:kZ5M1dWhNwIqXkXt5rzGHUOdaVzutN+bVVR59B6NgbIkIlmXtD86zgor5OCYclSoShfvBaSNIN1/ROzARu4zVI+fari5vBFLMxIPBOADNTyfc7JkH66o3RZSPhEYIKu/05jNfkbv8BW7ODKN7QvJDb7uRgZh5KGHPTbIKrZqvZg=,iv:aKE4GgGTtE3smCCuN5NgKG5EK08wN+E1d1glQZ21oC8=,tag:2PDITCTHTXGBm751PnY5AQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
