apiVersion: ENC[AES256_GCM,data:R4M=,iv:YOBo577JVXOfGsZTDCqMbVX7nCCzEaT6G03IYB3sbfg=,tag:iQypiyybOTfLgpN//4zv1Q==,type:str]
kind: ENC[AES256_GCM,data:2LPKJNrU,iv:fyPxF2Ty84WWMkS0ArxjNiqkB5U8PBvStX0Ry32Pmgc=,tag:1VQVKLU+cPuVYFcHutYlSg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:V3boVvp0FTerkebnJb8=,iv:5GpjB4KQojhNFWIwTES8lKiWhR+JCDrG8svcRlRkKPs=,tag:t/wssxygivm+O7nwdb72Vg==,type:str]
    namespace: ENC[AES256_GCM,data:jxOAOsH4,iv:Dq8QZmjchLJv+Pm4ptplqglUc3K1KhvDVqnQHgwcpI8=,tag:JN0RKGiZKWnGuSm+B/0q6Q==,type:str]
stringData:
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:9U4apbcRIPrxiulSxVeYbAExFOU=,iv:OiouubMGieqUU3nkNkZe7+DhoHFaA9ec8elYXGW4IoQ=,tag:P82m8XIVLcYmQtvrUImp1A==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:AARqFSFjpic07h4clsfjXu+1VgBJ73EhhpxATrhe1RjX+Q6mZ9DM5w==,iv:8jvHpX7l6P1LDieMlSqFkzdBrEKxBdIJeF/XwuP6c4Q=,tag:Yu0f80XQh+ji1QNIaCsK8g==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:5SFU/siiusPrLNX3+mObnd/FW3Cn3CUm+hkuS0ESIxC/uJxWKdXoV4Gsm0TFtYP+8MPqnTOYk0llCkqUDjmYfQ==,iv:7Z6JFqWZT8XB2+6SIc4VRAk4EZzlNYeopJp11H6YFms=,tag:m+EZbWjKrbISFc8VDtdKKA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:35WvPjGe,iv:ghgWYvQMlj+j2YKtShu2mjus4qgvo4DufYT0uHq8OIw=,tag:JpyDvr9farrlcmMkA+C1Eg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:HEwy/Qk1l+o5zsgBrkKOQQ+WV4fbDAHrhh679+dEknM=,iv:EH4rm3SL9O/40HeHhNleh6j5fc1RQATpeHyDXX+f4ms=,tag:jVrFv6ZNZ8j+Z709Gmeasw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:++4NYNJD,iv:SsGQdPU0sQewApZkEqQQznP5kswMldyETitJtbWLK14=,tag:FfRMUdOy5Tr5y043B6BDWA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:0QZ/sxkBr9Pz+C3gghKaNZzUjPR5VwO+1NV7zZ4oM5VCFDu5apWCdrdYn9G+SuvLPLf6CSjEhA==,iv:Sw0qEFmIoMnJYIsXylvQ7znvWNsEdI0DfZ5pYUBLI4c=,tag:dwono7tikPuZv2DKPBWITg==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVFJoNjVIVGswWkdnNFpF
              VXlZWGNuSFRPSHBvNFVIR3MyZk5ZRmxsM1hvCis4T0cyakwzc1RQSzVDL2cvbjFM
              b2dxdms2cTNJTGdtZG9KRzhxcXBUYXMKLS0tIEwrbnpLdlZBUHcvVElIVk9la1Na
              VllsSTJ1QTVnRkVuZmJvaWFtK05MS3MKfse4fMTNqjiVlWwKeKrqARxYXRiFqlAZ
              gRj1Pv0OmPygVCdg6NoZQORpCDlZuuF49d6qBVLbR5F7vr8259cEIw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T15:41:31Z"
    mac: ENC[AES256_GCM,data:b8aKys2/HbCxpB2jYMliWKtxN/frHWCdZBZS7wIsAv3mZT+Y9gFzJoyZt+ed68j01daP6ZVMYbebytI6Eqgpy0UgCK2vC81KLNXrkamkdyH0+/VgaZXfQGyj95K7g6lR3Uu7+CkuV3MGgLJBdrhH86o2qZVZ13Qq3mIvrI9JDmk=,iv:Xr8S0ujzuY8ONqT8Gzk7HFrBQiaJgQswnmT/sdh1vB0=,tag:p1BPvhB3/gsWcc8Dp7SuCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
