---
apiVersion: ocidex.io/v1alpha1
kind: OCIRegistry
metadata:
    name: quay-container-tools
    namespace: ocidex-dev
spec:
    name: "Quay.io — Container Tools (Red Hat)"
    type: generic
    url: quay.io
    visibility: public
    repositories:
        - containers/buildah
        - containers/podman
        - containers/skopeo
    tagPatterns:
        - semver
    scanMode: poll
    pollIntervalMinutes: 360
---
apiVersion: ocidex.io/v1alpha1
kind: OCIRegistry
metadata:
    name: quay-keycloak
    namespace: ocidex-dev
spec:
    name: "Quay.io — Keycloak"
    type: generic
    url: quay.io
    visibility: public
    repositories:
        - keycloak/keycloak
    tagPatterns:
        - semver
    scanMode: poll
    pollIntervalMinutes: 360
---
apiVersion: ocidex.io/v1alpha1
kind: OCIRegistry
metadata:
    name: quay-metallb
    namespace: ocidex-dev
spec:
    name: "Quay.io — MetalLB"
    type: generic
    url: quay.io
    visibility: public
    repositories:
        - metallb/controller
        - metallb/speaker
    tagPatterns:
        - semver
    scanMode: poll
    pollIntervalMinutes: 360
---
apiVersion: ocidex.io/v1alpha1
kind: OCIRegistry
metadata:
    name: ghcr-traefik
    namespace: ocidex-dev
spec:
    name: "GHCR — Traefik"
    type: ghcr
    url: ghcr.io
    visibility: public
    repositories:
        - traefik/traefik
    tagPatterns:
        - semver
    scanMode: poll
    pollIntervalMinutes: 360
---
apiVersion: ocidex.io/v1alpha1
kind: OCIRegistry
metadata:
    name: ghcr-flux
    namespace: ocidex-dev
spec:
    name: "GHCR — Flux Controllers"
    type: ghcr
    url: ghcr.io
    visibility: public
    repositories:
        - fluxcd/flux-cli
        - fluxcd/source-controller
        - fluxcd/kustomize-controller
        - fluxcd/helm-controller
        - fluxcd/notification-controller
        - fluxcd/image-reflector-controller
    tagPatterns:
        - semver
    scanMode: poll
    pollIntervalMinutes: 360
---
apiVersion: ocidex.io/v1alpha1
kind: OCIRegistry
metadata:
    name: ghcr-dex
    namespace: ocidex-dev
spec:
    name: "GHCR — Dex OIDC"
    type: ghcr
    url: ghcr.io
    visibility: public
    repositories:
        - dexidp/dex
    tagPatterns:
        - semver
    scanMode: poll
    pollIntervalMinutes: 360
