apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - dashboard.yaml
    - pipelines.yaml
    - triggers.yaml
    - interceptors.yaml
    - pruner.yaml
    - tailscale-ingress.yaml
patches:
    - patch: |-
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: feature-flags
            namespace: tekton-pipelines
          data:
            set-security-context: "true"
            disable-affinity-assistant: "true"
            coschedule: "disabled"
    # GKE Autopilot forbids binding roles to system:authenticated
    - patch: |-
          $patch: delete
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: tekton-pipelines-info
            namespace: tekton-pipelines
    - patch: |-
          $patch: delete
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: tekton-triggers-info
            namespace: tekton-pipelines
    - patch: |-
          $patch: delete
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: tekton-dashboard-info
            namespace: tekton-pipelines
