apiVersion: ENC[AES256_GCM,data:+YI=,iv:Xl7e/XLHrs8STsuZp3wwtjzOJGRy0P5wfON0lOAebqg=,tag:UjKhZ1wV1NW/IUngp+DSXg==,type:str]
kind: ENC[AES256_GCM,data:t9yntR5V,iv:3FrO4GpBpI7sNtUccMEnQ6e3JjQRlDEN8x24c/aMAEY=,tag:yAe3oUctWEbjSStysKwJ3w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SEjcx0OGG9l+8llX,iv:Ot5+0d3qBWqHg7VR5SpoIwFTrd748i6hoW1yXUiZ13w=,tag:gGjilcKxzPFdI6VFBEajTg==,type:str]
    namespace: ENC[AES256_GCM,data:bD7at1RiJqk=,iv:dguP0Cxe1Kh6G72ahUegaKD76dTlClWMXeGgabkcZgc=,tag:QePJLFvdfiIRSPUNJqgnjA==,type:str]
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:UnssCeLzzEeY5raOYHq/Gg/eIok1NkgJ5m4XD3Ok401erwGWtBbc1J8mO72hPACU4buta3/xwi50S2i3IaJKvKigYBBb9XKTvywbIXsEAxXqOZ5nwSuZpZk0hs6F,iv:UdAX3uutZxS81xhsJTGyNL6c1PmrOaGU5g5OPgBhabo=,tag:57w1pYk7rO1MdziOszOJqQ==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:gXJ8RrDo,iv:tA7LFz9+NkfrJL8V2J/AH7miXEogxjH4bnzxTy5HXNA=,tag:Hb2ddqtNV/PH5Kv5yANLng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoODBQbUdYWmFhemRUcCs2
            dGNRQVU0Y3Bjdmo3QmZHVS94cUxBR0IwY2drCnJ3N01Hck5NbWRtMGFUaGIzdnlZ
            Zm9CTk5mTkk1cUpOVUZMU3JobmE3cW8KLS0tIG9nUzRMMHpZVDlwYk5sdFRVSUUy
            a3phdVZUeXk2NStBQXl0c2JwaGdBWGsKv+B1L1x0/qfZ87eXDJY0LqqUJ5XRLTz5
            1svVpF89zmJG0BzlEa+veJETwJUmiblylfHzLtsEMTmKgoNQOxQNrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-09-06T15:33:39Z"
    mac: ENC[AES256_GCM,data:KlWlZzLG6p9siOTvJdiZpw+dmoEJ29va7GUshwa2IR2IBFX/oQwdERXUaXEDHuf4ZNtfNVGmJxuZREXvbsrSHPNV/Drm6mUbSA1iarAZKr/sfc8A7MS9JlOJGmhjp0Tg0yZK41LTUHpx6EdEm6fhrSRaof/P9Hl2LuodpwYpD4E=,iv:y630gDLUiWa7FZeTX7Nghpr1DEItoGNNdAGnjFKH7ng=,tag:dCylwrA/XthkB9pzMm8gkg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
