apiVersion: ENC[AES256_GCM,data:8Ng=,iv:PwOQI5ccoWlkuj2rVQF87sfwPeKw1F/zQpuIK5WrvWs=,tag:pIkpk7sFToR1sn0nRLhrLw==,type:str]
kind: ENC[AES256_GCM,data:ATWU46wa,iv:lJcYLUBU7eMRSAbHgxeGkGzm5zk5Rzs7R+Ima9K++Ug=,tag:24MBz1cjXKtJ/AHlCjG/Vg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WRIwvT3MswsswfIQ,iv:7Q6QGNHdDW9huL1UCJsahEUpd3O/2Fmp1tZHFSrIAVY=,tag:tEoAfNZNGwXeZu8A0pkiqQ==,type:str]
    namespace: ENC[AES256_GCM,data:V7lnwomhi7o=,iv:tqmgMmQT2UAYpbDPGWfxUZj/Nj5z4CJv102jlP/xoIY=,tag:IADad/wwO/1WVnEeUlpf/A==,type:str]
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:y6xOakMBvEBLl79B6e987V/NBcVk/jlWlvfDNe9j48kCwo41okse98yvN3iGLpZghufu0qjcuHTYzgTBDdg9Vuxlv98A3Q+VJ561ff7HTXgrhNqKU03Q26rhWznR,iv:XUmiFTzrTHxCueuVKM9G2gdUwJzhEtM0wSA7hm4tNRE=,tag:7fmLVs1EbdS+nSZ2YCBk6g==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:Qy2SpU4F,iv:T7oCm49bR8dIrv4mpoo4EIuXRUHwYxyBTH/vHC2nPq8=,tag:DHwP5L9IS6CXmar2tGbh4w==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZG80emtza0pwQTRLMEJx
            OHd5NDVkU0tESHpYVjBISkNudVZsVElMOXdFCkNkWWcxRE9MN1N4MnExbFl0dDZP
            QWpLTU12L2FuMEZtelZVcWVhSEc4N0UKLS0tIGVzMUlGRlRmWW04ZWY4WDVtQzg3
            QktMM3B5UlBrWmNNaEdxL2JXVEtMcEEKxhbLXmhGpF75FNjtc6Bc+EFWVh5awbSL
            cwR3cIy1HNHrfI0HSdrgUe+bKB4g/444g2sUY4+l0gJg0EBwBgK8iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T18:12:47Z"
    mac: ENC[AES256_GCM,data:LoCwBMmCeNqx9E3ujb34fvBtmaR4Yq2WV7m1x48B25Rw2vrWAwPoB3G1DZ4DZuwuzRqKAC7cmRzWr0wxN1nSiH9Z6RgAdrUnSHobM61j3xJlkAFchdShiCXV+igPjuKuUmKqZaP9jdqxOlcCzFlo9Fq8MAI5nHaV342byxiXVRc=,iv:x8pgCgMix2jStcIamoZCi7PsdcrFNLCzPYU1A0CBW+k=,tag:nG19uAhBLCLVxk40hOGwXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
