apiVersion: ENC[AES256_GCM,data:kjw=,iv:Csgali61q0it8rPFI/QxSeJLbxeGpCaTmktWs+CjTUo=,tag:Z4Z33Lg4Xcbmd0JqDaGZIw==,type:str]
kind: ENC[AES256_GCM,data:bWyjMrPU,iv:OqpbKKneNoxee7SvSE11rT9N6aVmaKvoJBWjrlRuAO0=,tag:5j+hzlEB6NzptI+aq2A8Dw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yM7Pq+ypmd6gLpGm,iv:1cSvFrb1z2KdnPRIPZjvG7cteu6JXrAv29JkFDjd3aw=,tag:InYTdP3CfS/K+HEkH5GxFA==,type:str]
    namespace: ENC[AES256_GCM,data:g4qC3eeeMag=,iv:gvT9G8HTxuQ5kfgf4lYKWrFxLhntfzZoNlrcje3TpMI=,tag:Z2ccyZf0IOyqSpiws5k8Sw==,type:str]
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:wLSCdffUz7wXReNo8PfUCOpiWGNJ6uNrjwYfnubCxbASKC0bNbuuP3FoBVVmINPfJ9JrEgkmcy3QBNC9AyBt+K/IAl7vDqb+QrSt2tZY3RAludYR19RlSFyaAdx/,iv:zDtq/6yHRfq8CgP3TGgYuJmOlLXvKEtWoj3sQj2paJ4=,tag:WIEuKMA/LWU0Ca6NVhlEuQ==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:f1WzSRky,iv:U8Tnx6kWOdaGsKsMCA1Jl5lqo4Sf2/DLFsrtw1ediyc=,tag:oPW3C70/JsDPtUhewX7zPQ==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNFJENm1JNklvNzk3T0hQ
              MEpqeFR1YUtsbGNYdUxaY1p0eUEwemJzMXhZCi9HdXJyR3gwRlltcXVkZlczK250
              b3BrRHliWm5KRVI3VmI3cmpCNkp3TFkKLS0tIExQeDdyY1VhaVQ2V2xmT213YjdR
              dGY3Tmw4ZnZGa25SblhnOE5KNFJSRmcKQyDdE8+7tKME+rK2jClQM2T0bgQOFvbP
              J1x8V8wXcdY/zRgzcB44RHndcU6nS2DwUL2W0w/k+niGE0xyvYBNQg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T16:42:40Z"
    mac: ENC[AES256_GCM,data:VQQvW26t2qEos1weNMk7PKszIBM7R3oueZHuy5naL/KNOx4K5zVQk9TxgTf+h0bEragsMbPB8f+v/uaBjpwNvEIKLzeV/Y0EuXOwKHQRAW45P0B9LJvNT7iKBwgx/k28hbnPZRpBVaIYKH1A4E1h8nmQTNXMC9XAXbQPu94GAFc=,iv:Q4+YgFVJkfFSeFxc6m3FCk+4xcMGAyBMEIG8AOYgJys=,tag:kFAJbCxIDqHXxmvVOZsQXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
