apiVersion: batch/v1
kind: CronJob
metadata:
    name: renovate
    namespace: renovate
spec:
    schedule: "@hourly"
    concurrencyPolicy: Forbid
    jobTemplate:
        spec:
            template:
                spec:
                    securityContext:
                        runAsNonRoot: true
                        seccompProfile:
                            type: RuntimeDefault
                    containers:
                        - name: renovate
                          image: renovate/renovate:latest
                          env:
                              - name: LOG_LEVEL
                                value: debug
                              - name: RENOVATE_AUTODISCOVER
                                value: "true"
                          envFrom:
                              - secretRef:
                                    name: renovate-env
                          securityContext:
                              allowPrivilegeEscalation: false
                              capabilities:
                                  drop:
                                      - ALL
                    restartPolicy: Never
