apiVersion: ENC[AES256_GCM,data:CCg=,iv:luK024PcIFwo1nniOVxCMSVDs6zlESod/3NCRuhVXFg=,tag:HKbaiLFgS5ly4CihrU5eTw==,type:str]
kind: ENC[AES256_GCM,data:7hn6IR5r,iv:HAQtTDRccjeYLkaakOKPqT7nS5P0cJR59SqoZ1I+c10=,tag:ORTfaDsjQSMJV17h7gU1Fw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XazmH9G6xpT41ilbc6odHuNQx6KzHSY=,iv:Cy43EaVmNAvk432+GCv+sJeEzQhrTZfPLjTY2PEwXK0=,tag:gJbKhjOlmJXevy9CqN+Tnw==,type:str]
    namespace: ENC[AES256_GCM,data:z8H/S6RwuogglLic2It3,iv:bbTCGvXoqoO1CBqZFeJfFLOU9tz0s0gAlM36QN6GUqk=,tag:ufGhDzBoWyaaOxsQcl7e/Q==,type:str]
stringData:
    OCIDEX_API_KEY: ENC[AES256_GCM,data:D5GytmzlSbS9EtzIWRQude41NdStVgnk7i4s63hTg3tQHiivIY6dwId+/ma5SM3jmfA=,iv:elouAdB8vHj1b+3Tz6ZT3egvia7ktHyfodLa3sGrY74=,tag:V/k7Lx7tGuddmvdKCjfNFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2L3JtZ242WjJtcU5iYXRH
            TnR4aU1xWHFvNW1SaHkrYm9GUkdHU2hDOEdvCmVaa3paeGphT0tyM0Z0RWdST3Vs
            SlhSS05HTHVtWEZwbDJyenNFdjllL0EKLS0tIEJWU2pVZ1duZWdlTi9VaEkrS2lF
            OU1VdHV4ekN5VjVrQnVLSWxiTnJUSkUKpnfOmpr23vxJMwzNyzylx11LoopGYA5w
            f6/9qEGX1iassdoXwpRp9uhyosy/HhtSA32z52hhWGW9zwLOnw7d/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-06-13T01:47:57Z"
    mac: ENC[AES256_GCM,data:RaVhU4XYYNVdVo+rIOYgtWbYZ7xSpP5aH8NXY1S3qi8PHHekSwquTuPzj+Djq03rk/uBPjCtsBPU0b9UJbcYqtW+kzmgo9gFQTu2Xi08RVcQJHJBfh3z0fJntg0IxoXJNafh07OYZC7pkFComnMAXm6BJWMBq4GpLO9loBscV3k=,iv:gF0Ce3aDYGDWJk7drmeD4QKt4YzCC1slGKNIXyeIA3Q=,tag:rbE3Iyq4ZDpYLmyZZ9e3mA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
