apiVersion: ENC[AES256_GCM,data:0H4=,iv:nxy2VaKKD5oBWCrDz+W5jLzkC8+GLRg7b0a9c01r3Xg=,tag:5MmNgd69wI3skEi4eSZgPw==,type:str]
kind: ENC[AES256_GCM,data:BUVXXZEa,iv:7w7VCV1ZIeASYXl1+JoOBUOfgsBBbPqAVDqAstKiewc=,tag:AGqlXs3pYsSgWbYIv1ihNA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x55/jWezzZ74EkLbwgkA0rm+QvZzrLg=,iv:e9Ka9csAP8m3oV7RwXEXTcgajc0p4GSm0YZO0oUh9o4=,tag:YZMxA92oVhUmySeYlK6jmw==,type:str]
    namespace: ENC[AES256_GCM,data:hcJp8qyL3xXRiX4k0guf,iv:4+vOfz01KhG4lwTsJfUOAzt26RHgPt/PAxUJ0zoYB7U=,tag:wMmm1MDEnG0JKui3ziRLfA==,type:str]
stringData:
    OCIDEX_API_KEY: ENC[AES256_GCM,data:T1H5zeCmvoI0nTS6m5kUi0tkuNRiLzlQf/Gb/2R3jlj86pl9U20TvmO3za/knI//jw8=,iv:qdvfOWR31ycPFvO2XYCjcszepcTXyyIabXdnZV8uvHs=,tag:0P/Qyss9W9Rz62o/c1NweA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM3Z6UnM3SDJPeWNTV001
            RldhRkVQNXJtTEkvekFia096UEpRTUxqZ1VjCnFmcWVPQ3NKR1JwQlJCOWtSNFZj
            djZiQ3NiWWJLZ3lzQ1ljdndXclhPRlkKLS0tIGpiajd0ZGJTcEVQNnBqWnhmMEJF
            Njc2d1daRFZRNEtpbjE2Um93QnRhK3cK/S+KPYUpBjg9d2LwwsHFuTOe/CRhVdG2
            P4pCPyQPP7NBCh4qSkiu4qXvbg/eKu1d7ZG3M0UUIIIIGk+er6llHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-06-13T00:48:17Z"
    mac: ENC[AES256_GCM,data:eHauyRll2JJMA2N4B4JvSE+OtaBTFBsKfSPV7Zzr5ngYy6/2dXfvmzJqTeNBX7V2h4SpoBK9W3B/gDtY0O2/P95D9BcNzxfkbaPKePW3lnQxQV+Q/+OU2++9lCxfV3hKNvb6LipJ4nQOAiKENYcnuScCF+LiC2SlXzSjxcxs5fY=,iv:TW41LLncmv01cVvVYdvhPawZf898N09tH0aX6jAqKtM=,tag:1m81OXjCxweQBX1l3EsdKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
