apiVersion: ENC[AES256_GCM,data:45Q=,iv:3vn3CTQ7qQ2IQXoTxaXIKBdoyf1a7xpmcwBoSW8z6Bg=,tag:WTp7peULCzO/X6Dgm9gWhQ==,type:str]
data:
    clientId: ENC[AES256_GCM,data:2dqsZIxcSUoPfVVbY64wHTyms58pWp9f,iv:R0F0Ap4zs0+uCyxUgiZdG0gk6wVaEq/Tz0iS2sJFxq0=,tag:UxKuudI0drx4meL31GMdZg==,type:str]
    clientSecret: ENC[AES256_GCM,data:1hjICOb49bnxySynA23/Spl0GqEtOuHjH8yLLph+pirYKMKH5FWWk2EJgSo+mSDb9Jg8jvcS8N8+2Gb6Bh3ZnIBhvpHt8RomRRFId9dUKoNnbEbR,iv:LjCAcPXygR1q6b4XsmHJk3rAsZklRde99T85PUUloZM=,tag:wRvsPnRp3FOk8PpgFyQuxA==,type:str]
kind: ENC[AES256_GCM,data:hw3fgV7J,iv:qP3tMgO4FPQXN2dwm/+4Y/QioxwL3O2Iease3MHuKJk=,tag:siT64Dima9TFbDbRZfntow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZUKr+dgyvRbPhgY7gT0k2bR/nGvV,iv:9jghr4Gu7bOtd6D9E05k32FUO4vtcw+U/ezovdrEDGk=,tag:CMYub/AW83iDiXmxIU8eqw==,type:str]
    namespace: ENC[AES256_GCM,data:2heZUI3Q9H0viaQ=,iv:16WES0GQtskBmAeDdcqt/R9RttDDFl2JJ0PBB8zdy1c=,tag:M60noB2lY2TAqMFaJoiKMw==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM3ZZL2RWb3pFcVFZMDJV
              cTZjQktkaDZXR0RWbXU1MXJ4azU4M0xmSkZBCm9LNUVJMjV2M3BGUDBHOHlmTC9y
              bkQ3NWxHME1kK0l2ZnRvQXlaMWQ3VHMKLS0tIGJ5M3htaEVacFB5VCtjYlo4U1pI
              SXJNcUdSVHA1WTJWYkJ0WVowS0F3K1kKqEfgSoldqjbe2127EZhedPXCfHt3DIhC
              cC+xvSmbmTE6++Y1u6a3H9UH/bJyVMWFJxmHnWKnK5C1H5Ecynuv3g==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T14:24:54Z"
    mac: ENC[AES256_GCM,data:9yvLozznaq0lPYtBr7kbfS4dlZppSRjV9NMLHxmHo5N3xpRt5tEUtp7P5xcy+s/RLtJsVQNgE+4IDpzSnLPKFD6Xk6wpgaI+bEQ+k97EjdksQ/mqmSz1Oe3I3BZlwkSWDsbz8zfAC6TBI5gjHPYT9UmU3ciPtiyMcyQL5zg+r68=,iv:0CGY+esGn5AVcbbCojZ7E1JxUh40ZaaFx6EayQr19o0=,tag:jdAUDAjPGz2W6Lhcwk3Mlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
