clientid: ENC[AES256_GCM,data:2+VFUeX1UUroeA4MqEXwAJI=,iv:gwTbnlA5xt7881OQC2nJZTgMYXz/Dkj2pTu2h8x/E64=,tag:FVlMenvd7l1hXV2MqMBfKQ==,type:str]
clientsecret: ENC[AES256_GCM,data:+0hMdi8QrRP98iRHRbg13CrkRIia2RtvfElTwrQWXx67HXSIyNztmFtU3FV8gjO9TYxBaciK6K7nBlKfXkjf,iv:xEcPUdCgXrCG9cYcx1wRMuKmIpvm3K2d/P6DEFbHlBg=,tag:faSjOZiYTeCteASn5lLf1Q==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbkZ5TE9OVm5Fb0RGT3ov
            VUtEUHZhNHIxOEZZaFRINjhwWThKek5aTUhnCmc0WDh5VjZIWkJsUWtDb0dMZ0FQ
            RmNvOXcxYzNSQUdSN0dpalkwbGpzL3MKLS0tIGRUTjJFWnhSenNMZ1RtUVpxeWpE
            OE5JVnF5TzQrWlNsdmlvRkxNRUpsQlEKEMuYolmEOeKMZDqKtEmumzDOWo5YOsgV
            TN5+K9fo7S+QrtTk4DkATQ6Afo4oE7/WLxZrSL5xkSoIVVmbKexm9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T14:10:49Z"
    mac: ENC[AES256_GCM,data:uoFFhw8SqcPMGMb3yja01pFubh2U2bnJ67ioZN8lcawqJUWsidZe1iw5rLPP03clZGDNuPSGjuFwjKh0Ypc6D1hsrPMkZ775a1V4nZoZl0KCc0WR47e9pyzEPCdnJ7CUQsAiPKtrsVzXfdtMY+ifd6GGzaIHXe31sVYJYjMpZw0=,iv:d9/nXaTOUuxhKCnzt77UNPWW6IA4Fi4XnHvMN/C7MTQ=,tag:iLmQokhlb/1B2TNw14a6Ow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
