apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ocidex-go-cache
    namespace: ocidex-ci
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ocidex-node-cache
    namespace: ocidex-ci
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
        requests:
            storage: 2Gi
