apiVersion: ENC[AES256_GCM,data:7YI=,iv:vuGecMZurozuEEG2DGqFxsP8MSQqzy1EBMgqdw4AU+Y=,tag:DDZQKhNQ5T+0yHm0HPUlVw==,type:str]
data:
    token: ENC[AES256_GCM,data:hFkZxV5I3KvZLMROoaXe03qy8WCn8PxRZ8OdcaDJxQjuIg4M/9IuAPzeWdXpvgRxDsUTUOyEBMpAf1c+VKfsXtC3wsl/mNaIX7AF5wsuq+83Cnes6xDF3eowjbFU4nFmrM5FDb1ifW5ses40Ed0ekUmJVkeTXkblAyvxsA==,iv:XyqlHOt6H6Vi7TnsYdc46IuAnNbU8mp8eUYx2QvcVZQ=,tag:yfs5UEV0Uo8zVxAfascKAA==,type:str]
kind: ENC[AES256_GCM,data:fcP+eTkA,iv:n+lRxgQNw9GqEYQeorR979giFhzM5UXMA9KnllTABI0=,tag:2ZLVRYKwZTCmRqe/uT1HEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bCct8n/eiNFNw2ZH,iv:HNur9ZM1lbweQkb2LyZMJjrnfOCdE3LuEljgvFlmX1Q=,tag:OCAdUxHXKC0QY7dTRd6q9A==,type:str]
    namespace: ENC[AES256_GCM,data:BRIciEeEy5PT,iv:xvMSrO4jy6jjh2Nu94z+ZT8W8MG6tWgeqRxEerifhag=,tag:pJb2W6tuLp0yhj21ZcHtEA==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcjBnL0hhNFhkZzhzK2po
              bDU0b1VXT3VBL2RuQXRjSDMySkxuUEN5N1I4ClVPOVYyTnFRSUdpYlBudWRoTjFi
              TDVFVTJzVVJvNzBITmVWcitGVkI1YmMKLS0tIGJhZ1hiN3VZc0VtRzgvSjhTMnJ3
              dVBsL3QvSkZQQXlaQk1FaFg1RWk1QzQKHpIW3EHXlF5UBziFRWNVSl/LVFAKE9O2
              m9QE050CYWpg/G9HzdzTKfk/Ny1KshqCYS1Lh0UEIucbwIs/tKLcVQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T21:41:59Z"
    mac: ENC[AES256_GCM,data:/wk+00SD1eDoF37QVeHUNYEsHuUoSXT9/J7v0w0tTbXWyl9Mhkn1NN12kgnm79WDD4jy3/RgFbLmY4/ejxp8GaD4NzX+9FFNrHOqcCDU8UpXprFMnavcObxE8dB7MLjbVP0CV0ZvS4SNHlOtDZGlS9JN1E/ADekTNKQtqP7t7bU=,iv:Aj7d05kU4GhUciMWbNUwZboOWiMSoVdqXBoj2Pmg7zQ=,tag:KcJDIzzIVv68wn5aS8uV+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
