apiVersion: ENC[AES256_GCM,data:DU4=,iv:u5Uh5UpYdOOxYDmImz9I6ApYHPVEqFiRrwdMta9MqN0=,tag:vBibfuuh3KXWA9zjfQm6AQ==,type:str]
kind: ENC[AES256_GCM,data:C+Qfs1V9,iv:SAXCVRPNtqsxbJ6+umlt9Iu1Apwo0MtOZtv/k+syHzk=,tag:mXC03vlcJhLMm9ES8PxLCQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EaTsU+jfw+FUiB96UqROxwfbiD+O,iv:mk2huGRu3C5sG8JVGSglTj8TyAveou49NksYaqBsWok=,tag:7Tca+LsCytfltpS981/BKA==,type:str]
    namespace: ENC[AES256_GCM,data:0mGlNM/EYVUe,iv:qPvILEy17dJhcXMH+15WB2YR1zWwZS93Nd5Go/xUaHc=,tag:FgEX5Ng8SGTME/Yt4B/A9A==,type:str]
type: ENC[AES256_GCM,data:NCip6RPx,iv:q/4w2evHL7dNKGIP6hxwt3yFR3NWjSIZzHrinjm9LdI=,tag:NOWbxszTVEcP2HM6nmd1dA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:5UqPkLL5MWaMV6tAzWpjj92JOJHbNwkjhqPIb262BfFjC4Rc+J8gT5dN067QjIlrHDjRoAy5RinHX0P0B/KE9XnjayZUfU6lr2YGwIAns7ind1JjFvhuv4jgLwUc,iv:2TAc8+jv5bSqZEcJJDoBz5NGODO2YWbuMj2zcOXfZaE=,tag:I93kdece6cJ3koGum4p8vA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNlJCSStkNTlXN3V3elZn
            NW9yRnk1TUNGSXVvaW1LKzdnNlBBb3ZkMVNNCmNnaWFudVlKMVBVU1NVb2ZoQVRK
            OEFGcVovT29ucCtDU0ZMZmovK1c3eVUKLS0tIHBmdVpYaDdBaEtqTDUzd1A3aUNs
            eVErR0NnS2tORDFzeFpvLzVHMG9BVzgKsRMWndRskcnV6KcEAQy7oUS8LCXmDhrQ
            qTly20jJT1QOTiy0VWNROZ/t5v1uwo0s4sNWaRP1788bwb2yoF8D1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-06-20T21:43:00Z"
    mac: ENC[AES256_GCM,data:1+WSdGPyZIg78JcVYLcNK0fCNdmqwhat8sTNvoeksEHwzGea9ruOUu5t1mqvq5jTDNzBrpAynLLcCoeFs58Se2H42bu8qmompXPGm3udDUFMJL6bEivsWs5H/fDphPYDum+zjahgd37NquQH+asLteRuKDqclp7AdGcqWtyY7Bs=,iv:Pk73hTj2G78oPINmrvHOPlLPD/WW7TGPLjLn7sG+CPA=,tag:FArt7veOtD/SzjNiODdNsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
