apiVersion: ENC[AES256_GCM,data:w1o=,iv:/XE0DlCq6kMfQktz4LydbM2zBHNe+AQkoZGeNHUrozU=,tag:absbw49wrAOPPUaz+tKbnA==,type:str]
data:
    token: ENC[AES256_GCM,data:bcZ9S30pnA0BHcwWyK34BJ0G9pBqM4fKqaX73NKcYYCiYOKYsXME2MIw08wE1XyQZtiHC44NgYJJOvhsqgL8nMbSZHArR7Aims7tvoH1Bt6K4Ac1WHl/dSzYwTc7S4FRiACqabqxCGaFVYl6wtZmFZlEVPC+BElK9XWPVQ==,iv:pJu9tk+bOJ3fYDaN5skRy1XRzgxsLFTLLbCmUgYcn/g=,tag:x7DvrMY+li4ZTN7KtoMkfA==,type:str]
kind: ENC[AES256_GCM,data:9905g9EX,iv:SO9nuL84Vbt1i5FeGaThSoiuK4tPDZMZ2MJQpmBwjEY=,tag:NMDGrU8Zhz7WpKTSz+vvKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:41/F4pZ2d3JBkfrr,iv:ePmTpiSvtxm/ZM1GY6eNawrYyFJpGB2rEODyKQ1s1b8=,tag:WFuCNv6guxqK1h5FheRs/A==,type:str]
    namespace: ENC[AES256_GCM,data:Qz+iZbtrCjOx,iv:C4oBgO8tuz+qeBdjWl7e6ZyL4rbob+Kb+lL6IM7IMWs=,tag:CXbxf7A8iOinhLAPW+kHMg==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OXBvR2p2WCtPNGVGTE1U
            ZEpmakh0MHIxeVBWT3h0R3VyRzNDQWlaNVM0ClRyYkI1UHRJbW1DTkc1THVrQnhK
            MTdXQmlYWGdaYTk1dk56U3dXZVZ1d0EKLS0tIGFDMHo0N1lHNXBwK0JkWEdFWVo4
            TnJOTWFiREpCQ1EwWFZCVmFrWE5VekUK77MB7BhlkIZLaD74JD0OkJ2W+Jt9g9Ml
            RvrBeFhK/n7EcoiuI6dRK7S9gMUesUgWyz/d2glknXTTrAvqeQPl+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T01:05:44Z"
    mac: ENC[AES256_GCM,data:2EO9Apk5WVaH/B5guHJoII8tOrFC0Ge8Kp5OrMBHXVuHWJ/F4/jr6FCD/2QwlWocdDrgK0TdM4RBgGbfg56LsTaCQ0kt2hHBVvFKb5OliDYwNE+KjOqkwQyHiclnoT+5Udipfhvi5OWTogQj0EaNRo6QFwEUbV1UR55ei6TVPpQ=,iv:83nFK2etaPLFS5ePOMSp+ip+9RJkqolE+WtSSbVMiso=,tag:iZvp5YE9LPsMY4zePJ2tDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
