apiVersion: ENC[AES256_GCM,data:MEg=,iv:JqIklUN9wfNFhayxFyoRcGzs23dDvECKzRMsZ95mlZE=,tag:6LZIHgFpQV9y9Y3NUwCNRQ==,type:str]
kind: ENC[AES256_GCM,data:3Tyv9YFl,iv:blOXYV/IhlgkNdg13N0S4Xmrgw4M2GBFXx33EXyjZY4=,tag:+aD84MD5SBtbXSAoEe3yLw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NZA0KQn/amHXCAn5RBiQk8QAcjFS,iv:tiiqjqp+Om4yE/rQOjw3J5i3ycmKgQ0UyOkPeBVSEg8=,tag:I3CtzlzPYB+nWBiCFF1bKA==,type:str]
    namespace: ENC[AES256_GCM,data:qn60KwWHAcMe,iv:vObFoz3ds5J691mWu5wztxl1GQ9ReewqUbPW33c3CBI=,tag:DveLlgd6cedc/ebXkhY+FQ==,type:str]
type: ENC[AES256_GCM,data:CRYxDHnb,iv:eCBXmYdXBlHEbfSjt07X/v7zzVq4VHNTWKGP7C5vi5w=,tag:qbpyuAtfTGs7cNJm1XL34w==,type:str]
stringData:
    token: ENC[AES256_GCM,data:iI5MCtsdkNoE+IcYWxOOzUoeyHB75jBk3QA2J5HKi2OuzTsQy5etRJKcl0FVGFG6xo7Oyuklv4hE+sdg6yUZsa7XxphDhc+a2tmNkp0+PoNJfgA0QVGdhiG0ymAP,iv:u+Wqu+gSq7U2Rb1AmZufUwjBoxxZQveYR7x+jlxZ5HM=,tag:we5U6Wn9UF0s8bNXgy5FQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVGx6TGNMQ2tsbzdZNW1L
            S0RlZDJpY2I1SGtob1BYNFhQeGs0UXBzY2prCklUa2Q0NW82TjUrMFRabXEyZ1pF
            RHdlQ0VtZENkV0lJLzVhZ3ZQOXVnS2sKLS0tIFNoZ2M1SWJMazU3VVFNNWJPUkhs
            MGpFTFBSMXdSQ2drNkVrbHUyZE82L1kK+/PizBd0SsYCGn8d+CRTNHBiY7E1DyWv
            9Luiulh0jK6MApZw/KpzRnFgq5iI4Uc/srLI8Ttey6YxDWp5EK7faQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-09-25T00:58:56Z"
    mac: ENC[AES256_GCM,data:LN2gJG1Mmem9rvrXdQxPMoOgSre4qRmozsC7fg9r608/IMZYX/9U3+mXtCjJL/TPcsGvcnQUWxNKcsYOPS6dSPhxtwt6lPfojkrO6QzA2stvVO28gqCiWMStuOgmfZ+5RRj9gFPJg21obr80xTqM4R2PjVKgsMWtI8miL3uAM/c=,iv:xZBGP/yt21Bmm56TiDNgJREc0ZT94d6doLMirYhZmFo=,tag:1kT7YWmJuPprp/E++9ZtKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
