apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - github-webhook.secret.yaml
    - pac-repository.yaml
    - pac-github.secret.enc.yaml
    - cache-pvcs.yaml
    - ghcr-docker-config.secret.enc.yaml
