apiVersion: ENC[AES256_GCM,data:a9M=,iv:Rl3e0gQsHByombEZDvWLuNB/v+xyuiriKdUYGyTHnJ4=,tag:5dT3/rTSrd6TaSl6Eu3afA==,type:str]
kind: ENC[AES256_GCM,data:UCZ47Fop,iv:m7KbFD59kCSQU6NHzBktUcl9imdK+N8ZESqVFKDfCwc=,tag:olnpRKz+9284objasUhXsQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:glwXqm3qyGZqmZkGXEY=,iv:zW1FAQPVcI0cQTZ7FrrqG+hZ4h2ki+7Ok5uozYa/nuY=,tag:3lKaBHyjtyugygpa7rfnvQ==,type:str]
    namespace: ENC[AES256_GCM,data:Jcfrf0YX6KRO,iv:C6+lAeswAw5V+LTGjgvn0HopAyc6Pq7syEXZmYj7ijM=,tag:LU52OakZNTeX2JuwSQ+C0Q==,type:str]
type: ENC[AES256_GCM,data:15loDLGt,iv:scDBTt3j1lUIoKJVYGHlQvLyKLQ4Naow6ZM8Khk1YPQ=,tag:RB+/IktxPWUvUmKfqiPJSQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:67WUt/FDlSyKZTEKD/A7vcJwXzHaHmBXDmyc5+8UW7J9bQcm2oqGZ930va27nShKvsU=,iv:iezWGKwATMRmw1FnnmqI7LyFB3T0b0mV0h4P5jNfhzs=,tag:2EaRJropgeiHtZCQ6Uv3jA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqR2xjNnlObnF0Z1RnWFk1
            bitlU0ttUVpxOGdVaS9lWlNkems0blJjaVVJCjlHTno4amVLM0dtSXZCZmFjTTVZ
            YnpVSzRKdTh6TEI1YVRkaWo1NXFSc1EKLS0tICtSamRvSk1WcGd1Y3lnbmY5VFE0
            Tmg3SGVxTnpjeUZDc3RQVlpIRyt0dU0KL0/VNos+MFCCZux4iVZFqJzRsBPRJUZX
            cGtjB6Zku1eYxiTa9vjE6X4UlR9w68WixFh2Ra8tp6mA6wUXL7Lf7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-08-02T21:09:52Z"
    mac: ENC[AES256_GCM,data:8H2gjPHA2uxHfeFeKy1F5/XM3eFkJyf+8O1B4OBY7LNdmFd86HgTq1m/8jk3Ef4/oECL7zZvvtUgqtjXCQdkJIn0Y4mX5vwI257r9yqW8vIfZINj8L6xflLEbPuazWvtHCKWwQJ7BtTojXdHsy8vvzCqpVCu3DUUm/sXzthH36c=,iv:Kbt6bE3Y5tvlFs0vAOESl6Ef5+C3ISLRTCsu454TNS8=,tag:XnNYVesAeB2GCFUngaRK+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
