apiVersion: ENC[AES256_GCM,data:3U8=,iv:a39sgTSODybnwYvDr/jHOFwX5UCpy6d4Q+/k9ZqNMo4=,tag:E8pLXx0VtEjtoA8NJXmuHA==,type:str]
kind: ENC[AES256_GCM,data:mce+gtqH,iv:FzxkLCYMjghVuJ/1UTTKEDEdYII07ZUQd85/qKg9NO0=,tag:oNYmZKWq05gWFy7bEOLb6g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NScdW2t0Mv4TRRjr7YQ=,iv:0yCm04ODbMBoLo6fjT137TYI9dO70huieSQZV5MckNg=,tag:C2SNXhaemHO+7whOEDOGPg==,type:str]
    namespace: ENC[AES256_GCM,data:J5nrV5G9OxJ6,iv:yn77hx01WFkJA4fwsdpKSWVjbx0BiaMmaef/I4CH1uY=,tag:TY5NkEKfzW/7OJv8ao1Zjw==,type:str]
type: ENC[AES256_GCM,data:XZWxvor/,iv:gcCE9qM5lE+3wQAE14Pm0nXaG0BkXBbmHoH2gAOg7F0=,tag:f2Nt1ToYAmioTwceNckgjA==,type:str]
stringData:
    key: ENC[AES256_GCM,data:g3VG7R0qlRHy+pa1mMtFsWI21835esTB9Xqkaikhr56yYqn7j7tZH+56dDWNPqQUdjc=,iv:lnvLArqIJXiWAsE5EZsJOXdTZx4ohx83dOfc4ixc4o0=,tag:TWtnDS1YQSHA6u5IlAydZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM1lTOVQ5L05ZVm1aQVU3
            czA0WS80OTRVRXhNUkhpdVpGOGF3UmZpL2lRCkpIdU1aTmxqd1cxUVFPaFNaalUy
            VjJTcTRIY21PMEtLdHZqVEVNT1lkNzQKLS0tIGJoOEUxU2grRHZqN29GWlFQakJI
            VTBONi9sNmdwV1FYN2l5NDZDV2xpR1kKafYhIlU2cf4RYKB98FDcFYrwyOxP+ufu
            yvfUPD9JCdJdlF2vEtJX0LaVnPxG8HHFJneK63HuYjbwP/P5dbOz7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-08-02T21:12:37Z"
    mac: ENC[AES256_GCM,data:/r2jtwlo7h2OXyZ3u74F15OnEp7q2AhDtRs/SOzBoHHxbJE8oa9qC/1in8eqROnHsW5dWgs2e97NHaFzZ1+dlm/JOt3e8UXtMjf/AmG9WS1PNoa/wrDyuSw+LAAGWYaUkPAM4jMcqKqWDlt2ZdDLrWhquVvp7mrgrvxIvnXz8tw=,iv:4AN03i8pEgYDEbrxiY4JEtlFUlITYa1+sgyagF0DeDQ=,tag:7dKHeuzoKOs9s37bnRWK6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
