apiVersion: ENC[AES256_GCM,data:e90=,iv:WlvOJygkc38Pox5j8W8eUeDKYIg0PvM0RzpSZsCuMDU=,tag:26BhX/Lb7DnhRpyza60YzQ==,type:str]
kind: ENC[AES256_GCM,data:fVFZM7vD,iv:dmQ2f/wAtfJ1f7NB0KymeAdtzaRN/PzWxxxsiCZ/j6E=,tag:w+OCLXkxIYUnk5TiuKMjWw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:ypGQSQDL0ex5DWdjINuTpw==,iv:2E+OmdyxKhSBdWD1mJKUvKyksrdN2WL4/Vn8HoFBZR0=,tag:F7A8FSZvr1yW4H2n2v7CwA==,type:str]
  namespace: ENC[AES256_GCM,data:U2E5y5u8wu0L,iv:vI24PbO7lxujUSWmkp73jC4iY/M+5E1ATnITer3hpE4=,tag:bzPg5IP9UwBRf0PT0yfZJQ==,type:str]
type: ENC[AES256_GCM,data:adn4QWfu,iv:VPKAkGltJfSuUfVgunXFf7RTwA7ZM58smYzQSXEXi84=,tag:r4Qckbh/kfa5onKXasBfJw==,type:str]
stringData:
  token: ENC[AES256_GCM,data:vUB1BalHSXCjCpoJfvtcfr589X1trw8GI1SlSeFDRpCcuL+03s2bL5dYFWJ1/eLQydLNgLrFWwk0I2j7134h/zmz+WgTAHRBSnxuSvcXsUsbT41iidm7spfD/6Pe,iv:TwdvRI1NpRKv/coURYLadMbd35+fsVvJIidgiTcQHdw=,tag:DBqsNhZ0wgBHomeE16PUrA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVmtFU25UWnlhK3lTcjJS
        UUxRVWhsbnE0OEN2bm5xNjE0WUtFS3h3VEJBCndRb2Q5VURTMDkvb3hiSFg4ek0z
        aXhhQjNXREEvbmMydXlOaS9MdFFJb0UKLS0tIG1jTEpDNzBUZklMVGxMRitDWVVh
        TjRmMzlORXhOYVdnUTNYMXNPZjJFNU0K/R4SQ3RRNqpLfqytRECd19lQDrANWVvM
        zWCQOavKuPvw613AXgJWEGmrSkpgmck9fAmFBbSMuGyX3Y/9QR/owA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
  lastmodified: "2026-06-13T23:11:35Z"
  mac: ENC[AES256_GCM,data:D6orroRfUjFK6SgUdBqg/c3NYiogt5OYtJb3o4w/q2DohHgbdAcrAekEcbOuTG3IT/vDLweCvVuCVbcxN5jtV5lj3i2UllA0ID6zSyA9TZ3NMdDyb8DHUZ+/g+PaPK6i25lmCSmkz16hkSSEk5/j1Zp7epqrP0cPn8+TAwoiX94=,iv:R663FhnbHZyTbpcNbbcCcgosLfoQGrZaalVcMYSTDnI=,tag:1oR3a+kwqbd/NgZoihIfYA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
