---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ocidex-pipeline
  namespace: ocidex-ci
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: .tektonic/generated
  sourceRef:
    kind: GitRepository
    name: ocidex
