apiVersion: ENC[AES256_GCM,data:gEA=,iv:Hb2WlBQNFpIVEqWHAzL5kGkYogKdAZj/7+86qXMDUBg=,tag:LU/y7HFo4ArmchSu1IgBJQ==,type:str]
data:
    ACCOUNT_ID: ENC[AES256_GCM,data:+22n696dR4M9nqnfabp3cnSML8S4CS6vffsTZjSc/75hSPensxnuGzPiW+o=,iv:z8L73N2zyYLZnH+ke6bb3SJUPyZArlYZ11rinXxjzS0=,tag:LlcAV7GDTpOXYcuv/7bUKw==,type:str]
    TOKEN: ENC[AES256_GCM,data:XBllr6APJEIJ1STJozqayVjK53OfAbLoe3a+gdHMXkJhcdw8JvkZrp12ps+Ya3NxsbGuePOgmBM=,iv:h7vk1eQ3xFntCFjvuwdAT6DZ7f2qiThruF2YV9VsB3w=,tag:GLBiqk0usYf+4LC2fcst9A==,type:str]
kind: ENC[AES256_GCM,data:cwcvJfQV,iv:6SSMeB9J1aYzuGy3v5ZUj93rexG5Ful00pDJKmZbnuw=,tag:I5dEIGVXwd0jM4Sn6RyL3g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d85dLIx7oxe5sw==,iv:NHS+vkIPj0SlD5MbjsDHvMlknh0p0bxpJwH3waUxEvI=,tag:2ZzHnErD2+FaDJ75AqwpsQ==,type:str]
    namespace: ENC[AES256_GCM,data:RtkbB46EMFf/SMFtpImlylB4,iv:DazbTTfmW3Txrf2JnNr8Q7SYVpVzdK/+EpKz6ti4SnE=,tag:6ByaSFVva8u7V11UPDufeQ==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVElKWDl4eDVDNEdscW9m
            NTJlUU9HQklUUDZvVmd3dldMTnBEN0p3clh3CkJVZ3B2ejhJMVB6SExvQ1l2RXdS
            bmpEcDNkVkZyUDZFN21NZ2lPYjB5a0UKLS0tIDVSRzR1aWQyUSs1VmJoRXJudmlX
            OVIxalB5K1h0WVBkV1RaSmlvYXArbU0KPE3WTPXSZSP++rAwEaUx7fwgsq7KtYYn
            K1b46Vc2bUhGx27QreL6yaywhnbbfXJQnkjWgoIOTIMl3Aez7q449g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T20:44:25Z"
    mac: ENC[AES256_GCM,data:NoSfDM0nJkMzfesFlBkVIxFXnYydD/7IEGrkxo06WmPFDQqCkB5LzKCbI9XtlXdjKVp3/XUGx88812hdqQ7Nr7SzIuuB3b0LWhp9FGnwz+No6FGk4caVHnt9AlK2g0+13DnkXovxhR/wsoCCKIYDrb86E5M94WeABKLy9C0Z3zE=,iv:RngaDffjqTsPTVWehKn3NVWt+ZtBJDNeOyF3SHKqHuY=,tag:OVwfQeBo0xHiyhU35IA/1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
