---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: cloudflare-gateway-controller
    namespace: flux-system
spec:
    interval: 5m0s
    url: https://github.com/pl4nty/cloudflare-kubernetes-gateway
    ref:
        tag: v0.10.1
