apiVersion: ENC[AES256_GCM,data:ik4=,iv:FmEJpWbmiJZmg8cbixwZZX9UrrzModdsm2Xnhfit3lc=,tag:gr6xg2oljqsIzjROgd7PsQ==,type:str]
kind: ENC[AES256_GCM,data:13DuXdbP,iv:qLFpkbXb6FQblcpAC51/XUzn7iC2XGHaGzJ0lhW5x6s=,tag:I9tecmJTVwyohU1o98umKQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k9HTbHsEa7QXIccRBMJeMorTMJs=,iv:m9IfoW+6rT2VrdQMMTFUElTp0E2y8rfZmwa8Sp1YeZA=,tag:OvrE5NViso2TmKSAH+19EA==,type:str]
    namespace: ENC[AES256_GCM,data:uovcZY9D1C0uDw==,iv:/xzmWbQyBqOcd5tVqGE18TxLKg0PFYlVBxdx6FOzBfY=,tag:Ark92jWmGVEW2Bx/Rp80Hw==,type:str]
type: ENC[AES256_GCM,data:3Tj+cqeZ,iv:Dws+nlDL6hS/yJIQPsOS4nPwGBK5FSrHcfZRmSnjrmE=,tag:MgCzr4vwMhUY/N+DqYOBIg==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:oO1b4dM=,iv:ZM5cdL90xBVAYZkE293S2GLGmHOeAOYWxtU725gd+9Y=,tag:t0wz/cvu6FSLr8YjifOy2Q==,type:str]
    admin-password: ENC[AES256_GCM,data:T7c6JDFwvOQ=,iv:jiPhgWq1Igjke8RY/OzOYrPSK913MUAvWO9L3p80uS8=,tag:9t5ZSMNsJ0fTEZJ/ah7yWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcUpvb2p0V2FaNTQvNy9m
            R3ZzdjErV3dZYUt0aitXYTZJTnZDd3p2V1M4ClpPZ2NjZ1dQSEtZK05UTzdDWTEr
            MmcyNUgyMXNCRlZkRWhvMlFxUUJwQmcKLS0tIHR0MWl6YzM4dTc1dUZQVCtLRVZ2
            Qmc2ZjQ4SVFhWWFzZ0NWRElwT3FMZ1EKQs2qqnf9ksG7NKh9uemLJgcrfh3+vOi/
            CquL//lZI5M8FTpZ6LRP9Nj5oh0Bnm3Ilibs37NRtsSsjwanNvMOvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-06-06T17:21:36Z"
    mac: ENC[AES256_GCM,data:OUnfY2XpZGa9WLcJSU8vwMt/OFrXQDNuldWShq8H7dyqYP4CRNJp4loE6mk5WiRde8zavr0sVAUmFrQlFxm50IQ+HI1wBjpa5fW4c6d/HozeBJDHfB5gh67Y9XYfaZ15jGDI4yufeBB1R7Awm0kZXVXvU0hhNgabXLR0Fq3yu0k=,iv:D8A0Mo4RpY5D+ucOLQCXHEKyIEVkCvZ0S05wf/BfL8A=,tag:0iWxG5+Qg6tyE+wE13QFdg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
