# Grafana moved several OSS charts (tempo, grafana, loki, ...) here and deprecated
# them in grafana/helm-charts.
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://grafana-community.github.io/helm-charts
