apiVersion: ENC[AES256_GCM,data:8+Q=,iv:1Ao/huCYVJM6/Q5ykzXuvXuWX8w0P9GPwLb1QjR3YXA=,tag:/J0R88DRiaDJ1F46ew3Jmw==,type:str]
kind: ENC[AES256_GCM,data:1Vjlj9Ot,iv:S3me8tXBfO7EDTY28xGWzbXDYM5Ut7Ue63lLPKNOMx8=,tag:I+a8Yn4oIzzYy+N001OHzg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ExrBRnc29398ph3j3EOrdvjBe4mYJYp8ZjrC,iv:nOjdpQyjjOzDcchTFW+s69qC8sw6m9vxevq8zKIrqZk=,tag:mTX4OfSmqmcNQhhubracTg==,type:str]
    namespace: ENC[AES256_GCM,data:B80f3NmhTKXWGGE4hQtfY+IH5A==,iv:EvBlvYA2JFM0J0UcCRX+ZBDEPz8qO1B+ssMLPIXNs6g=,tag:xlWUhYJVSKilGBCEwBcgEg==,type:str]
stringData:
    OCIDEX_API_KEY: ENC[AES256_GCM,data:r89Z1wT9XUjVCyswsCiUxpOVHhL2VmbCdYXepkA4ewafslWv+ShlkGW3oNZrE/6N4Qg=,iv:R8dFSq5hmVlg1vhtOHyJ/eBX1dfqKbPxgPHZ8glKli0=,tag:Ef+uMyzk6MJO43s/tQ3OGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxakwvQVh2TVRjU2E3WXow
            UzkyQlpYVGNCUU9FL2dNa1VFRTNKOTc0RWwwCjEzS3BVdm9lSnJTUHlMd2UzcytH
            N0dDWEhxOUdmdWg5d1hYQloyZDBjVUkKLS0tIEVGL1kwNE15MklLYlNwaXhwN3Nj
            Nmp6eThKdW5qVzAyUW9oeHl4enphWWMKJ/n2X8wkjdB062+ARcDsctD1ScZsQojA
            YbTSgiXiWru727kHrHKIpDRSy0WtENrLpy7Vt0rrwWBYnRU9/rdrPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-06-13T01:47:59Z"
    mac: ENC[AES256_GCM,data:NBxxwMCF0TR9BX/c4oUcyPh0Tzb3XZe0kmbkJonhfe2UR784YtLtvPbazxoBL5dHkpxCdACLqxxrcdzHzkmbVy+QnNF6euGdfYfZo+st3njxIYHXy0A+tO5uL+hCTiMUtCeWlkvUdJHirwBA4fLku3gV45B2jYHdUOn1mC0VX88=,iv:tH/kmy6wRF/ypY1ySMSaArO+IfqQF+3x+zf5hyDHAI0=,tag:T66S5MGXBRdoyKGX3jGyBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
