apiVersion: ENC[AES256_GCM,data:rno=,iv:io3TxDqaHAhofePMB+9eveiyK9ERAH81quvKyvhaIwA=,tag:WR+oy6O9OEGDsSTQgB4TPQ==,type:str]
kind: ENC[AES256_GCM,data:AkVitG2e,iv:NGjmtPqqiyoBqKylhkuNe0kQUtWbdxsgEihjbTnXOLQ=,tag:3dvJkUceKdffAuvn6rXULQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zuRGUZdaMdBOLuXZ4nL3qooCEr5b2YdI+iXQ,iv:vxSemH0EUmXmm1sI1z5rSMJWVRMid5FU79FDLvEzBig=,tag:WNnuG4Y7DRQvuum++zQT7w==,type:str]
    namespace: ENC[AES256_GCM,data:OsVjhgtLMX2UUE0IuGpib6Yu8A==,iv:7rI+Y9Av8IPfqcRX49cLs3+EQWQ+THlm6PN2Dk6GzH0=,tag:ztwOxOQBvEXsvh+B/6NFYg==,type:str]
stringData:
    OCIDEX_API_KEY: ENC[AES256_GCM,data:hr3bdkBSqAaBXwvjl7dS9ff8pGGoyn2fWyl2FFvW/W/fHDCSzNIe1xqTmrVmhHuvXHM=,iv:nHIW6q+syW3d3bwyt9WzrGKOch8u0/bZpBU1kR3l1c8=,tag:29s9BoXxvGwB8Q4QgG+DiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUk4xNXpPOWdmcnVCRGJQ
            NFdBZ3BKK1NRK2tvR0JwRVMxMXZkQko0cGhRCjBLS2kxRHIzSXJkWVdGekZFd0NI
            V0dsN3ZyWS9IMEh4cGtoTHlxR2J3d0UKLS0tIEV2WlRpZnN6TzYwdE9ONko2dkVn
            d2x2bjN6ZWMyQ1lWSk5DaStsaEgwNjQKPNkfzy3m0S0qb3KoaDt8AEPLVSStkCwI
            ziXEe/+9jE3ZGyigqR+CTx2qhyLfI1N4WsiEnxWLgd1ysfjeLo56wQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
    lastmodified: "2026-06-13T00:48:11Z"
    mac: ENC[AES256_GCM,data:GcvtKzjlVly0AsurLfyUy6ZUjndri8/tt1/KlCCHHREBt3mAY6Q36fgaWs6WgAu0w/5uMqmr8gZ13XhwHqM03A25FmUXEWca2EJsUP2oTPmeGcpLY60beox80ibShAAcO8qxrAn77LMqRHlEzu6jkBMBE/Zu0ZQxIkmbd72Z8ec=,iv:bmIMzSXDGNT98dccUJS6naC79GX+wuKh2htTJ3GLwIg=,tag:axbP65ig5rx57DhePfJvsg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
