apiVersion: ENC[AES256_GCM,data:Lvg=,iv:JsUZ+zcAYPf1fuMJ3x4Ice9r8ho2jFLEOpGdmQNQsMw=,tag:u6CwI+xbGSLIR0fkJ1Mrkg==,type:str]
data:
    client_id: ENC[AES256_GCM,data:Ky92OpvQUfTovnOP0BdNpy64HLk4qoI6,iv:j3T5uhhSv5StRW2DJoKalsne8ouWDaR7TgiiZsHV8cQ=,tag:5B8DzLQBFbAifdeZSDEb2g==,type:str]
    client_secret: ENC[AES256_GCM,data:nIdsMPAWYj9e38015m7vdEefL2H7Ll3jX8sTssUna5B5jfODCPOCicoYQ/VquvdXv1AjXO1s2fIKolRlCUJ5Frwlj2+Aj4CGzqflLdwIk7RkHqjQ,iv:Gju+3M98ZtJ6HEOdNUMw4sIm+Tq/IzWu35rr8UpcHd0=,tag:d0ew/ee2wYwUZhG3do26dA==,type:str]
kind: ENC[AES256_GCM,data:S/f4xHfH,iv:yAFkmFuHScGJxqcxQFqxQVDElhzPUCzWzv9F1jGNtQI=,tag:8VTOmHhrWRf9+Zrjs0Sv+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:i/MRz8oAmAO3dYQJNhQ=,iv:gW8B/zyJeTpkkSENFoO2S9g6wNNwPTQlxUQG8Cce+q8=,tag:0/rs3odfcfsZBDX1PfJKQg==,type:str]
    namespace: ENC[AES256_GCM,data:SuHnvc9qclGP6eBOgQ1m3+EB,iv:3+IPPksh/nMx9+cXfUHt3oHDhYTkM+NGn2Y5PHWnEsk=,tag:hmFld65tOnYyZuthHahI9A==,type:str]
sops:
    age:
        - recipient: age1cr8ez6j7px93cjswnrmll93k4kyghavrddll8gl0vqnrwr954dss4hmre3
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheEZSYWM3OFgxcE94aFdN
              YXlmWUJZanNTbGdWV0VPcWJUZnlNaExzS3djClJGNmQvQ1hLcHp2emJIdmRReGhD
              WndxK0lHWUV6R1FremJiTmY3VnRsTmMKLS0tIHFrTHhKYklFb1VxMk9TQUdneXl5
              WkdOU0JmYWdUL2hoOVRjOVNpaHZkNUEKWtQ/ev1BbkwNHfr4usNKflOjqdAsQVc9
              D8+/nbkUZ2KFy/qp8j7NhDxg5H0N2DEN3fdJKOlt7bhnRQtATH16Dw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T20:21:05Z"
    mac: ENC[AES256_GCM,data:9/a8Jc8mMmlu04URJNJ5MGXo45HGgn44Iwn/9Dq/0VPH8tDS6DrwBxTav9R0F9ugUvtLPUI4a5i7OY85nXapYnYYQr0C9mjOa0t2aFG0/6KVr7K/1T2DPaH8dOmWkcmE0pDmSyvrsoJY0sevc7S3Pn5wZm04fhpkbuLN8EAzZ0k=,iv:rn9/019bRr4XeMJhUcY00IiGLfr/Jqo9/kKVC4FZVMc=,tag:X7jzfQz0mwTZXfiz3zVHkw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
